---
title: Data Science for the Environment — Lecture Notes & Labs
author: Lauren Ponisio
site: bookdown::bookdown_site
documentclass: book
bibliography:
- refs/ecol_primer.bib
link-citations: true
output:
  bookdown::gitbook:
    split_bib: true
---

# Welcome 

This book accompanies the Fall 2025 course **BI 410/510L - Data Science for the Environment**, taught by **Prof. Lauren Ponisio**. The course equips students with practical skills to reproducibly analyze environmental data.

## Acknolwedgements 

In the spirit of open science, many of these lessons were inspired by other courses, including [Carl Boettiger](https://www.carlboettiger.info/) (Lab 2, Climate change), [Chris Paciorek](https://www.stat.berkeley.edu/users/paciorek/)(regular expressions, debugging) [Software carpentry](https://software-carpentry.org/) (Spatial labs, git), and [Aaron Clauset](https://www.colorado.edu/faculty/clauset/)(Networks).

```{r lab_setup, include=FALSE}
knitr::opts_chunk$set(error = TRUE, warning = TRUE, message = TRUE)
suppressPackageStartupMessages({
  install.packages("tidyverse", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("igraph", quietly = TRUE,repos = "http://cran.us.r-project.org")
  install.packages("bipartite", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("networkD3", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("vegan", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("stringr", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("bookdown", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("terra", quietly = TRUE, repos = "http://cran.us.r-project.org")
  install.packages("sf", quietly = TRUE, repos = "http://cran.us.r-project.org")

})
