<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>9 Geospatial data II: Vector-raster integration | Data Science for the Environment</title>
  <meta name="description" content="9 Geospatial data II: Vector-raster integration | Data Science for the Environment" />
  <meta name="generator" content="bookdown 0.45 and GitBook 2.6.7" />

  <meta property="og:title" content="9 Geospatial data II: Vector-raster integration | Data Science for the Environment" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 Geospatial data II: Vector-raster integration | Data Science for the Environment" />
  
  
  

<meta name="author" content="Lauren Ponisio" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="geospatial-data-i-data-types-rasters-and-vector-data.html"/>
<link rel="next" href="string-processing-debugging.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<script src="libs/d3-4.9.1/d3.min.js"></script>
<script src="libs/forceNetwork-binding-0.4.1/forceNetwork.js"></script>
<script src="libs/sankey-1/sankey.js"></script>
<script src="libs/sankeyNetwork-binding-0.4.1/sankeyNetwork.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Welcome</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#acknolwedgements"><i class="fa fa-check"></i><b>1.1</b> Acknolwedgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="syllabus.html"><a href="syllabus.html"><i class="fa fa-check"></i><b>2</b> Syllabus</a>
<ul>
<li class="chapter" data-level="2.1" data-path="syllabus.html"><a href="syllabus.html#course-overview"><i class="fa fa-check"></i><b>2.1</b> Course Overview</a></li>
<li class="chapter" data-level="2.2" data-path="syllabus.html"><a href="syllabus.html#the-7-fundamentals-wilson"><i class="fa fa-check"></i><b>2.2</b> The 7 Fundamentals (Wilson)</a></li>
<li class="chapter" data-level="2.3" data-path="syllabus.html"><a href="syllabus.html#coding-tools-and-practices"><i class="fa fa-check"></i><b>2.3</b> Coding Tools and Practices</a></li>
<li class="chapter" data-level="2.4" data-path="syllabus.html"><a href="syllabus.html#weekly-topics-and-readings"><i class="fa fa-check"></i><b>2.4</b> Weekly Topics and Readings</a></li>
<li class="chapter" data-level="2.5" data-path="syllabus.html"><a href="syllabus.html#assignments-and-grading"><i class="fa fa-check"></i><b>2.5</b> Assignments and Grading</a></li>
<li class="chapter" data-level="2.6" data-path="syllabus.html"><a href="syllabus.html#policies"><i class="fa fa-check"></i><b>2.6</b> Policies</a></li>
<li class="chapter" data-level="2.7" data-path="syllabus.html"><a href="syllabus.html#final-project"><i class="fa fa-check"></i><b>2.7</b> Final Project</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html"><i class="fa fa-check"></i><b>3</b> Key Programming Concepts</a>
<ul>
<li class="chapter" data-level="3.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#lecture-summary"><i class="fa fa-check"></i><b>3.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#learning-objectives"><i class="fa fa-check"></i><b>3.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="3.1.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#why-programming-concepts-matter"><i class="fa fa-check"></i><b>3.1.2</b> Why programming concepts matter</a></li>
<li class="chapter" data-level="3.1.3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#objects-and-basic-types"><i class="fa fa-check"></i><b>3.1.3</b> Objects and basic types</a></li>
<li class="chapter" data-level="3.1.4" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#assignments-vs.-expressions"><i class="fa fa-check"></i><b>3.1.4</b> Assignments vs. expressions</a></li>
<li class="chapter" data-level="3.1.5" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#functions-and-operators"><i class="fa fa-check"></i><b>3.1.5</b> Functions and operators</a></li>
<li class="chapter" data-level="3.1.6" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#core-data-structures"><i class="fa fa-check"></i><b>3.1.6</b> Core data structures</a></li>
<li class="chapter" data-level="3.1.7" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#comparisons-and-boolean-logic"><i class="fa fa-check"></i><b>3.1.7</b> Comparisons and boolean logic</a></li>
<li class="chapter" data-level="3.1.8" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#control-flow-if-and-for"><i class="fa fa-check"></i><b>3.1.8</b> Control flow: <code>if</code> and <code>for</code></a></li>
<li class="chapter" data-level="3.1.9" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#the-apply-family-vectorized-repetition"><i class="fa fa-check"></i><b>3.1.9</b> The <em>apply</em> family (vectorized repetition)</a></li>
<li class="chapter" data-level="3.1.10" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#writing-your-own-functions"><i class="fa fa-check"></i><b>3.1.10</b> Writing your own functions</a></li>
<li class="chapter" data-level="3.1.11" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#combining-steps-with-pipes"><i class="fa fa-check"></i><b>3.1.11</b> Combining steps with pipes</a></li>
<li class="chapter" data-level="3.1.12" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#r-vs.-python-a-quick-orientation"><i class="fa fa-check"></i><b>3.1.12</b> R vs. Python: a quick orientation</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#demo-programming-key-concepts-part-1-week-1"><i class="fa fa-check"></i><b>3.2</b> Demo: Programming Key Concepts part 1 (week 1)</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#starting-with-rstudio"><i class="fa fa-check"></i><b>3.2.1</b> Starting with RStudio</a></li>
<li class="chapter" data-level="3.2.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#individual-things"><i class="fa fa-check"></i><b>3.2.2</b> Individual things</a></li>
<li class="chapter" data-level="3.2.3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#assignment-statements"><i class="fa fa-check"></i><b>3.2.3</b> Assignment statements</a></li>
<li class="chapter" data-level="3.2.4" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#commands-that-operate-on-things"><i class="fa fa-check"></i><b>3.2.4</b> Commands that operate on things</a></li>
<li class="chapter" data-level="3.2.5" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#groups-of-things"><i class="fa fa-check"></i><b>3.2.5</b> Groups of things</a></li>
<li class="chapter" data-level="3.2.6" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#comparisons-and-booleans"><i class="fa fa-check"></i><b>3.2.6</b> Comparisons and Booleans</a></li>
<li class="chapter" data-level="3.2.7" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#control-statements---for-repeating-yourself"><i class="fa fa-check"></i><b>3.2.7</b> Control statements - for (repeating yourself)</a></li>
<li class="chapter" data-level="3.2.8" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#control-statements---if-making-choices"><i class="fa fa-check"></i><b>3.2.8</b> Control statements - if (making choices)</a></li>
<li class="chapter" data-level="3.2.9" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#creating-chunks"><i class="fa fa-check"></i><b>3.2.9</b> Creating chunks</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#demo-exponential-population-growth-week-2"><i class="fa fa-check"></i><b>3.3</b> Demo: Exponential Population Growth (week 2)</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#exponential-population-growth-model"><i class="fa fa-check"></i><b>3.3.1</b> Exponential population growth model</a></li>
<li class="chapter" data-level="3.3.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#simulate-plot-a-single-scenario"><i class="fa fa-check"></i><b>3.3.2</b> Simulate &amp; plot a single scenario</a></li>
<li class="chapter" data-level="3.3.3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#compare-two-growth-rates"><i class="fa fa-check"></i><b>3.3.3</b> Compare two growth rates</a></li>
<li class="chapter" data-level="3.3.4" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#in-class-challenge"><i class="fa fa-check"></i><b>3.3.4</b> In class challenge</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#discussion-reflection-reproducible-research-alston-rick-2020"><i class="fa fa-check"></i><b>3.4</b> Discussion &amp; Reflection — Reproducible Research Alston &amp; Rick (2020)</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#preclass-reflection-please-submit-short-answers-via-canvas"><i class="fa fa-check"></i><b>3.4.1</b> Pre‑class reflection (please submit short answers via canvas)</a></li>
<li class="chapter" data-level="3.4.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#inclass-smallgroup-prompts"><i class="fa fa-check"></i><b>3.4.2</b> In‑class small‑group prompts</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#lab-programming-key-concepts"><i class="fa fa-check"></i><b>3.5</b> Lab: Programming Key Concepts</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#lesson-overview"><i class="fa fa-check"></i><b>3.5.1</b> Lesson Overview</a></li>
<li class="chapter" data-level="3.5.2" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#review-the-seven-core-concepts"><i class="fa fa-check"></i><b>3.5.2</b> Review: The Seven Core Concepts</a></li>
<li class="chapter" data-level="3.5.3" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-1-population-dynamics"><i class="fa fa-check"></i><b>3.5.3</b> Question 1: Population dynamics</a></li>
<li class="chapter" data-level="3.5.4" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-2-using-operators-and-functions"><i class="fa fa-check"></i><b>3.5.4</b> Question 2: Using operators and functions</a></li>
<li class="chapter" data-level="3.5.5" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-3-storing-and-indexing-data"><i class="fa fa-check"></i><b>3.5.5</b> Question 3: Storing and indexing data</a></li>
<li class="chapter" data-level="3.5.6" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-4-storing-data-and-logical-indexing"><i class="fa fa-check"></i><b>3.5.6</b> Question 4: Storing data and logical indexing</a></li>
<li class="chapter" data-level="3.5.7" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-5-using-loops-to-repeat-calculations"><i class="fa fa-check"></i><b>3.5.7</b> Question 5: Using loops to repeat calculations</a></li>
<li class="chapter" data-level="3.5.8" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-6-making-the-model-stochastic-with-an-if-statement"><i class="fa fa-check"></i><b>3.5.8</b> Question 6: Making the model stochastic with an if statement</a></li>
<li class="chapter" data-level="3.5.9" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-7-creating-a-logistic-growth-function"><i class="fa fa-check"></i><b>3.5.9</b> Question 7: Creating a logistic growth function</a></li>
<li class="chapter" data-level="3.5.10" data-path="key-programming-concepts.html"><a href="key-programming-concepts.html#question-8-extra-credit-or-graduate-students"><i class="fa fa-check"></i><b>3.5.10</b> Question 8 (Extra credit or graduate students)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html"><i class="fa fa-check"></i><b>4</b> Using “The Tidyverse” for data manipulation and visualization</a>
<ul>
<li class="chapter" data-level="4.1" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#lecture-summary-1"><i class="fa fa-check"></i><b>4.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#learning-objectives-1"><i class="fa fa-check"></i><b>4.1.1</b> Learning Objectives</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#demo-introduction-to-the-tidyverse"><i class="fa fa-check"></i><b>4.2</b> Demo: Introduction to the Tidyverse</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#data-wrangling"><i class="fa fa-check"></i><b>4.2.1</b> Data wrangling</a></li>
<li class="chapter" data-level="4.2.2" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#data-visualization"><i class="fa fa-check"></i><b>4.2.2</b> Data visualization</a></li>
<li class="chapter" data-level="4.2.3" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#common-types-of-visualizations"><i class="fa fa-check"></i><b>4.2.3</b> Common types of visualizations</a></li>
<li class="chapter" data-level="4.2.4" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#fun-graph-references"><i class="fa fa-check"></i><b>4.2.4</b> Fun graph references:</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#discussion-reflection-coding-best-practices"><i class="fa fa-check"></i><b>4.3</b> Discussion &amp; Reflection — Coding Best Practices</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#why-these-practices"><i class="fa fa-check"></i><b>4.3.1</b> Why these practices</a></li>
<li class="chapter" data-level="4.3.2" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#readability-and-clarity"><i class="fa fa-check"></i><b>4.3.2</b> Readability and Clarity</a></li>
<li class="chapter" data-level="4.3.3" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#reproducibility"><i class="fa fa-check"></i><b>4.3.3</b> Reproducibility</a></li>
<li class="chapter" data-level="4.3.4" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#modularity-and-reuse"><i class="fa fa-check"></i><b>4.3.4</b> Modularity and Reuse</a></li>
<li class="chapter" data-level="4.3.5" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#documentation"><i class="fa fa-check"></i><b>4.3.5</b> Documentation</a></li>
<li class="chapter" data-level="4.3.6" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#testing-and-validation"><i class="fa fa-check"></i><b>4.3.6</b> Testing and Validation</a></li>
<li class="chapter" data-level="4.3.7" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#efficiency-after-correctness-and-clarity"><i class="fa fa-check"></i><b>4.3.7</b> Efficiency (after correctness and clarity)</a></li>
<li class="chapter" data-level="4.3.8" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#quick-checklist"><i class="fa fa-check"></i><b>4.3.8</b> Quick Checklist</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#lab-data-manipulation-and-visualization-using-the-tidyverse-student-version"><i class="fa fa-check"></i><b>4.4</b> Lab: Data manipulation and visualization using the Tidyverse (Student Version)</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#lesson-overview-1"><i class="fa fa-check"></i><b>4.4.1</b> Lesson Overview</a></li>
<li class="chapter" data-level="4.4.2" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#demo-evidence-for-global-climate-change"><i class="fa fa-check"></i><b>4.4.2</b> Demo: Evidence for Global Climate Change</a></li>
<li class="chapter" data-level="4.4.3" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#plotting-data-with-ggplot"><i class="fa fa-check"></i><b>4.4.3</b> Plotting Data with <code>ggplot</code></a></li>
<li class="chapter" data-level="4.4.4" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#lab-2-questions-exploring-and-visualizing-more-data-realted-to-global-climate-change."><i class="fa fa-check"></i><b>4.4.4</b> Lab 2 Questions: Exploring and visualizing more data realted to global climate change.</a></li>
<li class="chapter" data-level="4.4.5" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#demo-exploring-seasonal-oscillations"><i class="fa fa-check"></i><b>4.4.5</b> Demo: Exploring Seasonal Oscillations</a></li>
<li class="chapter" data-level="4.4.6" data-path="using-the-tidyverse-for-data-manipulation-and-visualization.html"><a href="using-the-tidyverse-for-data-manipulation-and-visualization.html#question-9-gradaute-student-or-extra-credit-summarize-the-data-of-your-choice."><i class="fa fa-check"></i><b>4.4.6</b> Question 9 (Gradaute student or Extra credit) : Summarize the data of your choice.</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html"><i class="fa fa-check"></i><b>5</b> Simulation-based hypothesis testing</a>
<ul>
<li class="chapter" data-level="5.1" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#lecture-summary-2"><i class="fa fa-check"></i><b>5.1</b> Lecture summary:</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#learning-objectives-2"><i class="fa fa-check"></i><b>5.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="5.1.2" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#hypothesis-testing"><i class="fa fa-check"></i><b>5.1.2</b> Hypothesis testing</a></li>
<li class="chapter" data-level="5.1.3" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#ab-testing"><i class="fa fa-check"></i><b>5.1.3</b> A/B testing</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#demo-ab-testing-with-mauna-loa-co%E2%82%82"><i class="fa fa-check"></i><b>5.2</b> Demo: A/B Testing with Mauna Loa CO₂</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#import-co%E2%82%82-monthly-data"><i class="fa fa-check"></i><b>5.2.1</b> Import CO₂ monthly data</a></li>
<li class="chapter" data-level="5.2.2" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#create-the-outcome-and-define-ab-groups"><i class="fa fa-check"></i><b>5.2.2</b> Create the outcome and define A/B groups</a></li>
<li class="chapter" data-level="5.2.3" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#observed-effect-difference-in-means"><i class="fa fa-check"></i><b>5.2.3</b> Observed effect (difference in means)</a></li>
<li class="chapter" data-level="5.2.4" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#permutation-test-twosided-blocked-by-month"><i class="fa fa-check"></i><b>5.2.4</b> Permutation test (two‑sided), <strong>blocked by month</strong></a></li>
<li class="chapter" data-level="5.2.5" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#challenge-problem-seasonal-amplitude-ab-test"><i class="fa fa-check"></i><b>5.2.5</b> Challenge Problem — Seasonal amplitude A/B test</a></li>
<li class="chapter" data-level="5.2.6" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#biodiversity-metrics-%CE%B1-%CE%B2-%CE%B3-diversity"><i class="fa fa-check"></i><b>5.2.6</b> Biodiversity metrics: α, β, γ diversity</a></li>
<li class="chapter" data-level="5.2.7" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#functional-diversity-trait-based"><i class="fa fa-check"></i><b>5.2.7</b> Functional diversity (trait-based)</a></li>
<li class="chapter" data-level="5.2.8" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#beta-diversity-among-site-turnover"><i class="fa fa-check"></i><b>5.2.8</b> Beta diversity (among-site turnover)</a></li>
<li class="chapter" data-level="5.2.9" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#biotic-homgenization-and-traits"><i class="fa fa-check"></i><b>5.2.9</b> Biotic homgenization and traits</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#discussion-reflection-ponisio-et-al.-2016-on-farm-habitat-restoration-counters-biotic-homogenization-in-intensively-managed-agriculture"><i class="fa fa-check"></i><b>5.3</b> Discussion &amp; Reflection: Ponisio et al. (2016): On-farm habitat restoration counters biotic homogenization in intensively managed agriculture</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#preclass-reflection-please-submit-short-answers-via-canvas-2"><i class="fa fa-check"></i><b>5.3.1</b> Pre‑class reflection (please submit short answers via canvas)</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#lab-do-the-bees-at-hedgerows-and-weedy-field-margins-controls-have-the-same-distribution-of-traits"><i class="fa fa-check"></i><b>5.4</b> Lab: Do the bees at hedgerows and weedy field margins (controls) have the same distribution of traits?</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#question-1-practicing-the-data-subsetting-tools-from-dplyr"><i class="fa fa-check"></i><b>5.4.1</b> Question 1: Practicing the data subsetting tools from dplyr</a></li>
<li class="chapter" data-level="5.4.2" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#demo-joining-data"><i class="fa fa-check"></i><b>5.4.2</b> Demo: Joining data</a></li>
<li class="chapter" data-level="5.4.3" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#question-2-1"><i class="fa fa-check"></i><b>5.4.3</b> Question 2</a></li>
<li class="chapter" data-level="5.4.4" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#lab-question-3"><i class="fa fa-check"></i><b>5.4.4</b> Lab Question 3</a></li>
<li class="chapter" data-level="5.4.5" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#demo-do-the-bees-at-hedgerows-and-weedy-field-margins-controls-have-the-same-distribution-of-traits"><i class="fa fa-check"></i><b>5.4.5</b> Demo: Do the bees at hedgerows and weedy field margins (controls) have the same distribution of traits?</a></li>
<li class="chapter" data-level="5.4.6" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#lab-question-4"><i class="fa fa-check"></i><b>5.4.6</b> Lab Question 4</a></li>
<li class="chapter" data-level="5.4.7" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#question-5"><i class="fa fa-check"></i><b>5.4.7</b> Question 5</a></li>
<li class="chapter" data-level="5.4.8" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#demo-interpreting-the-results"><i class="fa fa-check"></i><b>5.4.8</b> Demo: Interpreting the results</a></li>
<li class="chapter" data-level="5.4.9" data-path="simulation-based-hypothesis-testing.html"><a href="simulation-based-hypothesis-testing.html#question-6"><i class="fa fa-check"></i><b>5.4.9</b> Question 6</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html"><i class="fa fa-check"></i><b>6</b> Version control and collaboration with git and github</a>
<ul>
<li class="chapter" data-level="6.1" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#lecture-summary-3"><i class="fa fa-check"></i><b>6.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#learning-objectives-3"><i class="fa fa-check"></i><b>6.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="6.1.2" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#hypothetical-paper-writing"><i class="fa fa-check"></i><b>6.1.2</b> Hypothetical: Paper Writing</a></li>
<li class="chapter" data-level="6.1.3" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#solution"><i class="fa fa-check"></i><b>6.1.3</b> Solution</a></li>
<li class="chapter" data-level="6.1.4" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#why-use-git-and-github"><i class="fa fa-check"></i><b>6.1.4</b> Why Use Git and GitHub?</a></li>
<li class="chapter" data-level="6.1.5" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#a-simple-two-person-git-workflow"><i class="fa fa-check"></i><b>6.1.5</b> A Simple Two-Person Git Workflow</a></li>
<li class="chapter" data-level="6.1.6" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#five-essential-git-commands"><i class="fa fa-check"></i><b>6.1.6</b> Five Essential Git Commands</a></li>
<li class="chapter" data-level="6.1.7" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-status"><i class="fa fa-check"></i><b>6.1.7</b> 1) <code>git status</code></a></li>
<li class="chapter" data-level="6.1.8" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-add"><i class="fa fa-check"></i><b>6.1.8</b> 2) <code>git add</code></a></li>
<li class="chapter" data-level="6.1.9" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-commit--m-message"><i class="fa fa-check"></i><b>6.1.9</b> 3) <code>git commit -m "message"</code></a></li>
<li class="chapter" data-level="6.1.10" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-push"><i class="fa fa-check"></i><b>6.1.10</b> 4) <code>git push</code></a></li>
<li class="chapter" data-level="6.1.11" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-pull"><i class="fa fa-check"></i><b>6.1.11</b> 5) <code>git pull</code></a></li>
<li class="chapter" data-level="6.1.12" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#git-command-summary"><i class="fa fa-check"></i><b>6.1.12</b> git command summary</a></li>
<li class="chapter" data-level="6.1.13" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#i-cannot-push-my-commit"><i class="fa fa-check"></i><b>6.1.13</b> I cannot push my commit!?</a></li>
<li class="chapter" data-level="6.1.14" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#introducing-the-shell"><i class="fa fa-check"></i><b>6.1.14</b> Introducing the shell</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#discussion-reflection-trisos-et-al.-2021-decoloniality-and-antioppressive-practices-for-a-more-ethical-ecology"><i class="fa fa-check"></i><b>6.2</b> Discussion &amp; Reflection: Trisos et al. (2021): Decoloniality and anti‑oppressive practices for a more ethical ecology</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#article-embedded"><i class="fa fa-check"></i><b>6.2.1</b> Article (embedded)</a></li>
<li class="chapter" data-level="6.2.2" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#individual-reflection-short-written-responses"><i class="fa fa-check"></i><b>6.2.2</b> Individual reflection (short written responses)</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#lab-git-and-github"><i class="fa fa-check"></i><b>6.3</b> Lab: Git and Github</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#question-1-1"><i class="fa fa-check"></i><b>6.3.1</b> Question 1</a></li>
<li class="chapter" data-level="6.3.2" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#question-2-2"><i class="fa fa-check"></i><b>6.3.2</b> Question 2</a></li>
<li class="chapter" data-level="6.3.3" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#question-3-v1-partners"><i class="fa fa-check"></i><b>6.3.3</b> Question 3 v1 (partners)</a></li>
<li class="chapter" data-level="6.3.4" data-path="version-control-and-collaboration-with-git-and-github.html"><a href="version-control-and-collaboration-with-git-and-github.html#question-3-v2-solo-project"><i class="fa fa-check"></i><b>6.3.4</b> Question 3 v2 (solo project)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ecological-networks.html"><a href="ecological-networks.html"><i class="fa fa-check"></i><b>7</b> Ecological networks</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ecological-networks.html"><a href="ecological-networks.html#lecture-summary-4"><i class="fa fa-check"></i><b>7.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="ecological-networks.html"><a href="ecological-networks.html#learning-objectives-4"><i class="fa fa-check"></i><b>7.1.1</b> Learning objectives</a></li>
<li class="chapter" data-level="7.1.2" data-path="ecological-networks.html"><a href="ecological-networks.html#from-data-to-networks"><i class="fa fa-check"></i><b>7.1.2</b> From data to networks</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="ecological-networks.html"><a href="ecological-networks.html#linearalgebra-essentials-for-ecological-networks"><i class="fa fa-check"></i><b>7.2</b> Linear‑algebra essentials for ecological networks</a></li>
<li class="chapter" data-level="7.3" data-path="ecological-networks.html"><a href="ecological-networks.html#demo-linear-algebra-for-networks"><i class="fa fa-check"></i><b>7.3</b> Demo: Linear algebra for networks</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ecological-networks.html"><a href="ecological-networks.html#in-class-challenge-matrix-vector-multiplication-with-plantpollinator-data"><i class="fa fa-check"></i><b>7.3.1</b> In-class challenge: Matrix &amp; vector multiplication with plant–pollinator data</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ecological-networks.html"><a href="ecological-networks.html#core-network-properties-formulas-intuition-tools"><i class="fa fa-check"></i><b>7.4</b> Core network properties (formulas, intuition, tools)</a></li>
<li class="chapter" data-level="7.5" data-path="ecological-networks.html"><a href="ecological-networks.html#demo-calculating-network-metrics-and-using-null-models"><i class="fa fa-check"></i><b>7.5</b> Demo: Calculating network metrics and using null models</a></li>
<li class="chapter" data-level="7.6" data-path="ecological-networks.html"><a href="ecological-networks.html#network-visualization"><i class="fa fa-check"></i><b>7.6</b> Network visualization</a></li>
<li class="chapter" data-level="7.7" data-path="ecological-networks.html"><a href="ecological-networks.html#demo-create-a-graph-from-oba-data-visualize-it"><i class="fa fa-check"></i><b>7.7</b> Demo: Create a graph from OBA data, visualize it</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="ecological-networks.html"><a href="ecological-networks.html#in-class-visualization-challange-1."><i class="fa fa-check"></i><b>7.7.1</b> In class: Visualization challange 1.</a></li>
<li class="chapter" data-level="7.7.2" data-path="ecological-networks.html"><a href="ecological-networks.html#in-class-visualization-challange-2."><i class="fa fa-check"></i><b>7.7.2</b> In class: Visualization challange 2.</a></li>
<li class="chapter" data-level="7.7.3" data-path="ecological-networks.html"><a href="ecological-networks.html#further-reading-software"><i class="fa fa-check"></i><b>7.7.3</b> Further reading &amp; software</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="ecological-networks.html"><a href="ecological-networks.html#discussion-reflection-yeakel-et-al.-2014-collapse-of-an-ecological-network-in-ancient-egypt"><i class="fa fa-check"></i><b>7.8</b> Discussion &amp; Reflection: Yeakel et al. (2014): Collapse of an ecological network in Ancient Egypt</a>
<ul>
<li class="chapter" data-level="7.8.1" data-path="ecological-networks.html"><a href="ecological-networks.html#article-embedded-1"><i class="fa fa-check"></i><b>7.8.1</b> Article (embedded)</a></li>
<li class="chapter" data-level="7.8.2" data-path="ecological-networks.html"><a href="ecological-networks.html#reflection-and-in-class-discussion-questions"><i class="fa fa-check"></i><b>7.8.2</b> Reflection and in-class discussion Questions</a></li>
</ul></li>
<li class="chapter" data-level="7.9" data-path="ecological-networks.html"><a href="ecological-networks.html#lab-food-webs-network-measures-student-version"><i class="fa fa-check"></i><b>7.9</b> Lab: Food Webs &amp; Network Measures (Student Version)</a>
<ul>
<li class="chapter" data-level="7.9.1" data-path="ecological-networks.html"><a href="ecological-networks.html#lesson-overview-2"><i class="fa fa-check"></i><b>7.9.1</b> Lesson Overview</a></li>
<li class="chapter" data-level="7.9.2" data-path="ecological-networks.html"><a href="ecological-networks.html#lab-question-1-creating-our-foodwebs-based-on-body-sizes."><i class="fa fa-check"></i><b>7.9.2</b> Lab question 1: Creating our foodwebs based on body sizes.</a></li>
<li class="chapter" data-level="7.9.3" data-path="ecological-networks.html"><a href="ecological-networks.html#lab-question-2-breaking-the-networks-into-time-periods"><i class="fa fa-check"></i><b>7.9.3</b> Lab question 2: Breaking the networks into time periods</a></li>
<li class="chapter" data-level="7.9.4" data-path="ecological-networks.html"><a href="ecological-networks.html#lab-question-3-visualize-the-networks"><i class="fa fa-check"></i><b>7.9.4</b> Lab question 3: Visualize the networks</a></li>
<li class="chapter" data-level="7.9.5" data-path="ecological-networks.html"><a href="ecological-networks.html#references"><i class="fa fa-check"></i><b>7.9.5</b> References</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html"><i class="fa fa-check"></i><b>8</b> Geospatial data I: data types (rasters and vector data)</a>
<ul>
<li class="chapter" data-level="8.1" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#lecture-summary-5"><i class="fa fa-check"></i><b>8.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#learning-objectives-5"><i class="fa fa-check"></i><b>8.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="8.1.2" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#raster-data"><i class="fa fa-check"></i><b>8.1.2</b> Raster Data</a></li>
<li class="chapter" data-level="8.1.3" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#in-class-challange-1-extent-change-with-crs-change"><i class="fa fa-check"></i><b>8.1.3</b> In class challange 1: Extent Change with CRS Change</a></li>
<li class="chapter" data-level="8.1.4" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#in-class-challenge-2-reproject-then-plot-a-digital-terrain-model"><i class="fa fa-check"></i><b>8.1.4</b> In class challenge 2: Reproject, then Plot a Digital Terrain Model</a></li>
<li class="chapter" data-level="8.1.5" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#vector-data"><i class="fa fa-check"></i><b>8.1.5</b> Vector data</a></li>
<li class="chapter" data-level="8.1.6" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#in-class-challange-3-plot-polygon-by-attribute"><i class="fa fa-check"></i><b>8.1.6</b> In class challange 3: Plot Polygon by Attribute</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#discussion-reflection-halofsky-et-al.-2020-changing-wildfire-changing-forests-the-effects-of-climate-change-on-fire-regimes-and-vegetation-in-the-pacific-northwest-usa"><i class="fa fa-check"></i><b>8.2</b> Discussion &amp; Reflection: Halofsky et al. 2020: Changing wildfire, changing forests: the effects of climate change on fire regimes and vegetation in the Pacific Northwest, USA</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#article-embedded-2"><i class="fa fa-check"></i><b>8.2.1</b> Article (embedded)</a></li>
<li class="chapter" data-level="8.2.2" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#in-class-discussion-prompts"><i class="fa fa-check"></i><b>8.2.2</b> In-class discussion prompts</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="geospatial-data-i-data-types-rasters-and-vector-data.html"><a href="geospatial-data-i-data-types-rasters-and-vector-data.html#lab-spatial-data-1-oregon-fires-student-version"><i class="fa fa-check"></i><b>8.3</b> Lab: Spatial data 1: Oregon Fires (Student Version)</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html"><i class="fa fa-check"></i><b>9</b> Geospatial data II: Vector-raster integration</a>
<ul>
<li class="chapter" data-level="9.1" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#lecture-summary-6"><i class="fa fa-check"></i><b>9.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#learning-objectives-6"><i class="fa fa-check"></i><b>9.1.1</b> Learning Objectives</a></li>
<li class="chapter" data-level="9.1.2" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-1-crop-to-vector-points-extent"><i class="fa fa-check"></i><b>9.1.2</b> In-class challenge 1: Crop to Vector Points Extent</a></li>
<li class="chapter" data-level="9.1.3" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-2-extract-raster-height-values-for-plot-locations"><i class="fa fa-check"></i><b>9.1.3</b> In class challenge 2: Extract Raster Height Values For Plot Locations</a></li>
<li class="chapter" data-level="9.1.4" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-4-import-plot-additional-points"><i class="fa fa-check"></i><b>9.1.4</b> In class challenge 4: Import &amp; Plot Additional Points</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#dicussion-reflection-debugging-in-r"><i class="fa fa-check"></i><b>9.2</b> Dicussion &amp; Reflection: Debugging in R</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#basic-debugging-strategies"><i class="fa fa-check"></i><b>9.2.1</b> 1) Basic debugging strategies</a></li>
<li class="chapter" data-level="9.2.2" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#rs-interactive-debugging-tools"><i class="fa fa-check"></i><b>9.2.2</b> R’s interactive debugging tools</a></li>
<li class="chapter" data-level="9.2.3" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#some-common-causes-of-bugs"><i class="fa fa-check"></i><b>9.2.3</b> Some common causes of bugs</a></li>
<li class="chapter" data-level="9.2.4" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#tips-for-avoiding-bugs-and-catching-errors"><i class="fa fa-check"></i><b>9.2.4</b> Tips for avoiding bugs and catching errors</a></li>
<li class="chapter" data-level="9.2.5" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#how-to-get-help-online"><i class="fa fa-check"></i><b>9.2.5</b> How to get help online</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="geospatial-data-ii-vector-raster-integration.html"><a href="geospatial-data-ii-vector-raster-integration.html#lab-spatial-data-2-working-with-oba-data-student-version"><i class="fa fa-check"></i><b>9.3</b> Lab: Spatial data 2: Working with OBA data (Student Version)</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="string-processing-debugging.html"><a href="string-processing-debugging.html"><i class="fa fa-check"></i><b>10</b> String Processing &amp; Debugging</a>
<ul>
<li class="chapter" data-level="10.1" data-path="string-processing-debugging.html"><a href="string-processing-debugging.html#lecture-summary-7"><i class="fa fa-check"></i><b>10.1</b> Lecture summary</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="string-processing-debugging.html"><a href="string-processing-debugging.html#learning-objectives-7"><i class="fa fa-check"></i><b>10.1.1</b> Learning objectives</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="string-processing-debugging.html"><a href="string-processing-debugging.html#in-class-challenge-what-will-the-regular-expression-oorgani.eb-match"><i class="fa fa-check"></i><b>10.2</b> In class challenge: What will the regular expression <code>^[Oo]rgani.e\b</code> match?</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="string-processing-debugging.html"><a href="string-processing-debugging.html#in-class-challenge-2-how-would-i-extract-an-email-address-from-an-arbitrary-text-string"><i class="fa fa-check"></i><b>10.2.1</b> In class challenge 2: How would I extract an email address from an arbitrary text string?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="final-project-1.html"><a href="final-project-1.html"><i class="fa fa-check"></i><b>11</b> Final project</a>
<ul>
<li class="chapter" data-level="11.1" data-path="final-project-1.html"><a href="final-project-1.html#final-project-objective"><i class="fa fa-check"></i><b>11.1</b> Final project objective</a></li>
<li class="chapter" data-level="11.2" data-path="final-project-1.html"><a href="final-project-1.html#final-project-topic-selection-first-final-project-assignment"><i class="fa fa-check"></i><b>11.2</b> Final project topic selection (first final project assignment)</a></li>
<li class="chapter" data-level="11.3" data-path="final-project-1.html"><a href="final-project-1.html#final-project-office-hours-discussion-second-final-project-assignment"><i class="fa fa-check"></i><b>11.3</b> Final project office hours discussion (second final project assignment)</a></li>
<li class="chapter" data-level="11.4" data-path="final-project-1.html"><a href="final-project-1.html#final-project-annotated-bibliography-third-final-project-assignment"><i class="fa fa-check"></i><b>11.4</b> Final project annotated bibliography (third final project assignment)</a>
<ul>
<li class="chapter" data-level="11.4.1" data-path="final-project-1.html"><a href="final-project-1.html#overview"><i class="fa fa-check"></i><b>11.4.1</b> Overview</a></li>
<li class="chapter" data-level="11.4.2" data-path="final-project-1.html"><a href="final-project-1.html#learning-objectives-8"><i class="fa fa-check"></i><b>11.4.2</b> Learning objectives</a></li>
<li class="chapter" data-level="11.4.3" data-path="final-project-1.html"><a href="final-project-1.html#requirements"><i class="fa fa-check"></i><b>11.4.3</b> Requirements</a></li>
<li class="chapter" data-level="11.4.4" data-path="final-project-1.html"><a href="final-project-1.html#how-to-search-effectively-google-scholar-tips"><i class="fa fa-check"></i><b>11.4.4</b> How to search effectively (Google Scholar tips)</a></li>
<li class="chapter" data-level="11.4.5" data-path="final-project-1.html"><a href="final-project-1.html#recommended-workflow"><i class="fa fa-check"></i><b>11.4.5</b> Recommended workflow</a></li>
<li class="chapter" data-level="11.4.6" data-path="final-project-1.html"><a href="final-project-1.html#what-each-entry-should-include"><i class="fa fa-check"></i><b>11.4.6</b> What each entry should include</a></li>
<li class="chapter" data-level="11.4.7" data-path="final-project-1.html"><a href="final-project-1.html#template-copy-for-each-source"><i class="fa fa-check"></i><b>11.4.7</b> Template (copy for each source)</a></li>
<li class="chapter" data-level="11.4.8" data-path="final-project-1.html"><a href="final-project-1.html#author-surname-et-al.-year.-title."><i class="fa fa-check"></i><b>11.4.8</b> Author Surname et al. (Year). <em>Title</em>.</a></li>
<li class="chapter" data-level="11.4.9" data-path="final-project-1.html"><a href="final-project-1.html#example-of-intext-citation-references"><i class="fa fa-check"></i><b>11.4.9</b> Example of in‑text citation &amp; references</a></li>
<li class="chapter" data-level="11.4.10" data-path="final-project-1.html"><a href="final-project-1.html#rubric"><i class="fa fa-check"></i><b>11.4.10</b> Rubric</a></li>
<li class="chapter" data-level="11.4.11" data-path="final-project-1.html"><a href="final-project-1.html#submission-checklist"><i class="fa fa-check"></i><b>11.4.11</b> Submission checklist</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="final-project-1.html"><a href="final-project-1.html#literature-review-and-workflow-plan-fourth-final-project-assignment"><i class="fa fa-check"></i><b>11.5</b> Literature review and workflow plan (fourth final project assignment)</a>
<ul>
<li class="chapter" data-level="11.5.1" data-path="final-project-1.html"><a href="final-project-1.html#literature-review-i.e.-the-introduction-section-of-your-final-project"><i class="fa fa-check"></i><b>11.5.1</b> Literature review (i.e., the introduction section of your final project)</a></li>
<li class="chapter" data-level="11.5.2" data-path="final-project-1.html"><a href="final-project-1.html#dataset-identification"><i class="fa fa-check"></i><b>11.5.2</b> Dataset identification</a></li>
<li class="chapter" data-level="11.5.3" data-path="final-project-1.html"><a href="final-project-1.html#workflow-plan"><i class="fa fa-check"></i><b>11.5.3</b> Workflow plan</a></li>
<li class="chapter" data-level="11.5.4" data-path="final-project-1.html"><a href="final-project-1.html#rubric-1"><i class="fa fa-check"></i><b>11.5.4</b> Rubric</a></li>
<li class="chapter" data-level="11.5.5" data-path="final-project-1.html"><a href="final-project-1.html#submission-checklist-1"><i class="fa fa-check"></i><b>11.5.5</b> Submission Checklist</a></li>
<li class="chapter" data-level="11.5.6" data-path="final-project-1.html"><a href="final-project-1.html#optional-scaffold-copy-into-your-working-doc"><i class="fa fa-check"></i><b>11.5.6</b> Optional scaffold (copy into your working doc)</a></li>
</ul></li>
<li class="chapter" data-level="11.6" data-path="final-project-1.html"><a href="final-project-1.html#final-project-rubric-10-pts-total-1-pt-extra-credit"><i class="fa fa-check"></i><b>11.6</b> Final Project Rubric (10 pts total + 1 pt extra credit)</a></li>
<li class="chapter" data-level="11.7" data-path="final-project-1.html"><a href="final-project-1.html#poster-presentation-rubric-10-pts-total"><i class="fa fa-check"></i><b>11.7</b> Poster Presentation Rubric (10 pts total)</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Data Science for the Environment</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="geospatial-data-ii-vector-raster-integration" class="section level1 hasAnchor" number="9">
<h1><span class="header-section-number">9</span> Geospatial data II: Vector-raster integration<a href="geospatial-data-ii-vector-raster-integration.html#geospatial-data-ii-vector-raster-integration" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="lecture-summary-6" class="section level2 hasAnchor" number="9.1">
<h2><span class="header-section-number">9.1</span> Lecture summary<a href="geospatial-data-ii-vector-raster-integration.html#lecture-summary-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This week we will learn how to crop a raster using the extent of a vector layer. We will also cover how to extract values from a raster that occur within a set of polygons, or in a buffer (surrounding) region around a set of points. We will also import spatial points stored in <code>.csv</code> (Comma Separated Value) format into R as an <code>sf</code> spatial object. Lastly, we will reproject data imported from an ESRI <code>shapefile</code> format, export the reprojected data as an ESRI <code>shapefile</code>, and plot raster and vector data as layers in the same plot. The reading is about R’s debugging tools and in the lab we will create a spatial points layer for the bee occurences, and overlay bioregion vector data. These demos are based on Software Carpentery’s spatial data lessons.</p>
<div id="learning-objectives-6" class="section level3 hasAnchor" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> Learning Objectives<a href="geospatial-data-ii-vector-raster-integration.html#learning-objectives-6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For Monday, we will:</p>
<ul>
<li>Use the <code>crop()</code> function to crop a raster object.</li>
<li>Use the <code>extract()</code> function to extract pixels from a raster object that fall
within a particular extent boundary.</li>
<li>Use the <code>ext()</code> function to define an extent.</li>
</ul>
<p>For Wednesday, we will;</p>
<ul>
<li>Import .csv files containing x,y coordinate locations into R as a data frame.</li>
<li>Convert a data frame to a spatial object.</li>
<li>Export a spatial object to a text file.</li>
</ul>
<p>Here’s a visualization of the types of data we are using (same as last week).</p>
<p><img src="fig/lidarTree-height.png" alt="DTM vs DSM vs CHM" /></p>
<p>First let’s load the data.</p>
<p><strong>Part 1: Crop a Raster to Vector Extent</strong></p>
<p>We often work with spatial layers that have different spatial extents (illustration of extents as a reminder below). The spatial extent of a vector layer or R spatial object represents the geographic
“edge” or location that is the furthest north, south east and west. Thus it represents the overall geographic coverage of the spatial object.</p>
<p><img src="fig/dc-spatial-vector/spatial_extent.png" alt="Extent illustration" /> Image Source: National
Ecological Observatory Network (NEON)</p>
<p>The graphic below illustrates the extent of several of the spatial layers that
we have worked with last week + some new data:</p>
<ul>
<li>Area of interest (AOI) – blue</li>
<li>Roads and trails – purple</li>
<li>Vegetation plot locations (marked with white dots)– black</li>
<li>A canopy height model (CHM) in GeoTIFF format – green</li>
</ul>
<p>CHM is a raster, but we want it as a vector layer, so we can convert it using the function <code>st_as_sf</code>.</p>
<p>Now we can visualize all of our datasets.</p>
<p><img src="08-geospatial-II_files/figure-html/compare-data-extents-1.png" width="672" />
You can see the CHM raster is much larger than our areas of interest.</p>
<p>Frequent use cases of cropping a raster file include reducing file size and
creating maps. Sometimes we have a raster file that is much larger than our
study area or area of interest (as we have now). It is often more efficient to crop the raster
to the extent of our study area to reduce file sizes as we process our data.
Cropping a raster can also be useful when creating pretty maps so that the
raster layer matches the extent of the desired vector layers.</p>
<p><strong>Crop a Raster Using Vector Extent</strong></p>
<p>We can use the <code>crop()</code> function to crop a raster to the extent of another
spatial object. To do this, we need to specify the raster to be cropped and the
spatial object that will be used to crop the raster. R will use the <code>extent</code> of
the spatial object as the cropping boundary.</p>
<p>To illustrate this, we will crop the Canopy Height Model (CHM) to only include
the area of interest (AOI). Let’s start by plotting the full extent of the CHM
data and overlay where the AOI falls within it. The boundaries of the AOI will
be colored blue, and we use <code>fill = NA</code> to make the area transparent.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb1-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb1-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb1-2" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> CHM_HARV_df, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb1-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb1-3" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">name =</span> <span class="st">&quot;Canopy Height&quot;</span>, <span class="at">colors =</span> <span class="fu">terrain.colors</span>(<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb1-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb1-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> aoi_boundary_HARV, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/crop-by-vector-extent-1.png" width="672" /></p>
<p>Now that we have visualized the area of the CHM we want to subset, we can
perform the cropping operation. We are going to <code>crop()</code> function from the
raster package to create a new object with only the portion of the CHM data
that falls within the boundaries of the AOI.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb2-1" tabindex="-1"></a>CHM_HARV_Cropped <span class="ot">&lt;-</span> <span class="fu">crop</span>(<span class="at">x =</span> CHM_HARV, <span class="at">y =</span> aoi_boundary_HARV)</span></code></pre></div>
<p>Now we can plot the cropped CHM data, along with a boundary box showing the
full CHM extent. However, remember, since this is raster data, we need to
convert to a data frame in order to plot using <code>ggplot</code>. To get the boundary
box from CHM, the <code>st_bbox()</code> will extract the 4 corners of the rectangle that
encompass all the features contained in this object. The <code>st_as_sfc()</code> converts
these 4 coordinates into a polygon that we can plot:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-1" tabindex="-1"></a>CHM_HARV_Cropped_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(CHM_HARV_Cropped, <span class="at">xy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-2" tabindex="-1"></a></span>
<span id="cb3-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-3" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb3-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> <span class="fu">st_as_sfc</span>(<span class="fu">st_bbox</span>(CHM_HARV)), <span class="at">fill =</span> <span class="st">&quot;green&quot;</span>,</span>
<span id="cb3-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-5" tabindex="-1"></a>          <span class="at">color =</span> <span class="st">&quot;green&quot;</span>, <span class="at">alpha =</span> .<span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb3-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-6" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> CHM_HARV_Cropped_df,</span>
<span id="cb3-7"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-7" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb3-8"><a href="geospatial-data-ii-vector-raster-integration.html#cb3-8" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">name =</span> <span class="st">&quot;Canopy Height&quot;</span>, <span class="at">colors =</span> <span class="fu">terrain.colors</span>(<span class="dv">10</span>)) </span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/show-cropped-area-1.png" width="672" /></p>
<p>The plot above shows that the full CHM extent (plotted in green) is much larger
than the resulting cropped raster. Our new cropped CHM now has the same extent
as the <code>aoi_boundary_HARV</code> object that was used as a crop extent (blue border
below).</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb4-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-2" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> CHM_HARV_Cropped_df,</span>
<span id="cb4-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-3" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb4-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-4" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> aoi_boundary_HARV, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb4-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-5" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">name =</span> <span class="st">&quot;Canopy Height&quot;</span>, <span class="at">colors =</span> <span class="fu">terrain.colors</span>(<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb4-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb4-6" tabindex="-1"></a>  <span class="fu">coord_sf</span>()</span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/view-crop-extent-1.png" width="672" /></p>
<p>We can look at the extent of all of our other objects for this field site.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb5-1" tabindex="-1"></a><span class="fu">ext</span>(CHM_HARV)</span></code></pre></div>
<pre><code>## SpatExtent : 731453, 733150, 4712471, 4713838 (xmin, xmax, ymin, ymax)</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb7-1" tabindex="-1"></a><span class="fu">ext</span>(CHM_HARV_Cropped)</span></code></pre></div>
<pre><code>## SpatExtent : 732128, 732251, 4713209, 4713359 (xmin, xmax, ymin, ymax)</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb9-1" tabindex="-1"></a><span class="fu">ext</span>(aoi_boundary_HARV)</span></code></pre></div>
<pre><code>## SpatExtent : 732128.016925, 732251.102892, 4713208.71096, 4713359.17112 (xmin, xmax, ymin, ymax)</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb11-1" tabindex="-1"></a><span class="fu">ext</span>(plot_locations_sp_HARV)</span></code></pre></div>
<pre><code>## SpatExtent : 731405.307, 732275.307, 4712844.977, 4713846.299 (xmin, xmax, ymin, ymax)</code></pre>
<p>Our plot location extent is not the largest but is larger than the AOI
Boundary. It would be nice to see our vegetation plot locations plotted on top
of the Canopy Height Model information.</p>
</div>
<div id="in-class-challenge-1-crop-to-vector-points-extent" class="section level3 hasAnchor" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> In-class challenge 1: Crop to Vector Points Extent<a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-1-crop-to-vector-points-extent" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li>Crop the Canopy Height Model to the extent of the study plot locations.</li>
<li>Plot the vegetation plot location points on top of the Canopy Height Model.</li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-1" tabindex="-1"></a>CHM_plots_HARVcrop <span class="ot">&lt;-</span> <span class="fu">crop</span>(<span class="at">x =</span> CHM_HARV, <span class="at">y =</span> plot_locations_sp_HARV)</span>
<span id="cb13-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-2" tabindex="-1"></a></span>
<span id="cb13-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-3" tabindex="-1"></a>CHM_plots_HARVcrop_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(CHM_plots_HARVcrop, <span class="at">xy =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-4" tabindex="-1"></a></span>
<span id="cb13-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-5" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb13-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-6" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> CHM_plots_HARVcrop_df,</span>
<span id="cb13-7"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-7" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb13-8"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-8" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">name =</span> <span class="st">&quot;Canopy Height&quot;</span>, <span class="at">colors =</span> <span class="fu">terrain.colors</span>(<span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb13-9"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-9" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> plot_locations_sp_HARV) <span class="sc">+</span></span>
<span id="cb13-10"><a href="geospatial-data-ii-vector-raster-integration.html#cb13-10" tabindex="-1"></a>  <span class="fu">coord_sf</span>()</span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/challenge-code-crop-raster-points-1.png" width="672" /></p>
<p>In the plot above all the vegetation plot locations
(black dots) appear on the Canopy Height Model raster layer except for one. One
is situated on the blank space to the left of the map. Why?</p>
<p>A modification of the first figure in this demo is below, showing the
relative extents of all the spatial objects. Notice that the extent for our
vegetation plot layer (black) extends further west than the extent of our CHM
raster (bright green). The <code>crop()</code> function will make a raster extent smaller,
it will not expand the extent in areas where there are no data. Thus, the
extent of our vegetation plot layer will still extend further west than the
extent of our (cropped) raster data (dark green).</p>
<p><strong>Define an Extent</strong></p>
<p>So far, we have used a vector layer to crop the extent of a raster dataset.
Alternatively, we can also the <code>ext()</code> function to define an extent to be
used as a cropping boundary. This creates a new object of class extent. Here we
will provide the <code>ext()</code> function our xmin, xmax, ymin, and ymax (in that
order).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb14-1" tabindex="-1"></a>new_extent <span class="ot">&lt;-</span> <span class="fu">ext</span>(<span class="fl">732161.2</span>, <span class="fl">732238.7</span>, <span class="dv">4713249</span>, <span class="dv">4713333</span>)</span>
<span id="cb14-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb14-2" tabindex="-1"></a><span class="fu">class</span>(new_extent)</span></code></pre></div>
<pre><code>## [1] &quot;SpatExtent&quot;
## attr(,&quot;package&quot;)
## [1] &quot;terra&quot;</code></pre>
<p><strong>Function Tip</strong></p>
<p>The extent can be created from a numeric vector (as shown above), a matrix, or
a list. For more details see the <code>ext()</code> function help file
(<code>?terra::ext</code>).</p>
<p>Once we have defined our new extent, we can use the <code>crop()</code> function to crop
our raster to this extent object.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb16-1" tabindex="-1"></a>CHM_HARV_manual_cropped <span class="ot">&lt;-</span> <span class="fu">crop</span>(<span class="at">x =</span> CHM_HARV, <span class="at">y =</span> new_extent)</span></code></pre></div>
<p>To plot this data using <code>ggplot()</code> we need to convert it to a dataframe.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb17-1" tabindex="-1"></a>CHM_HARV_manual_cropped_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(CHM_HARV_manual_cropped, <span class="at">xy =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Now we can plot this cropped data. We will show the AOI boundary on the same
plot for scale.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb18-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb18-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb18-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> aoi_boundary_HARV, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">fill =</span> <span class="cn">NA</span>) <span class="sc">+</span></span>
<span id="cb18-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb18-3" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> CHM_HARV_manual_cropped_df,</span>
<span id="cb18-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb18-4" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb18-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb18-5" tabindex="-1"></a>  <span class="fu">scale_fill_gradientn</span>(<span class="at">name =</span> <span class="st">&quot;Canopy Height&quot;</span>, <span class="at">colors =</span> <span class="fu">terrain.colors</span>(<span class="dv">10</span>)) </span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/show-manual-crop-area-1.png" width="672" /></p>
<p><strong>Part 2: Extract Raster Pixels Values Using Vector Polygons</strong></p>
<p>Often we want to extract values from a raster layer for particular locations -
for example, plot locations that we are sampling on the ground. For example, we can extract
all pixel values within 20 m of our x,y point of interest. These can then be
summarized into some value of interest (e.g. mean, maximum, total).</p>
<p><img src="fig/BufferSquare.png" alt="Image shows raster information extraction using 20m polygon boundary." />
Image Source: National Ecological Observatory Network (NEON)</p>
<p>To do this in R, we use the <code>extract()</code> function. The <code>extract()</code> function
requires:</p>
<ul>
<li>The raster that we wish to extract values from,</li>
<li>The vector layer containing the polygons that we wish to use as a boundary or
boundaries,</li>
<li>we can tell it to store the output values in a data frame using
<code>raw = FALSE</code> (this is optional).</li>
</ul>
<p>We will begin by extracting all canopy height pixel values located within our
<code>aoi_boundary_HARV</code> polygon which surrounds the tower located at the NEON
Harvard Forest field site.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb19-1" tabindex="-1"></a>tree_height <span class="ot">&lt;-</span> <span class="fu">extract</span>(<span class="at">x =</span> CHM_HARV, <span class="at">y =</span> aoi_boundary_HARV, <span class="at">raw =</span> <span class="cn">FALSE</span>)</span>
<span id="cb19-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb19-2" tabindex="-1"></a></span>
<span id="cb19-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb19-3" tabindex="-1"></a><span class="fu">str</span>(tree_height)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    18450 obs. of  2 variables:
##  $ ID          : num  1 1 1 1 1 1 1 1 1 1 ...
##  $ HARV_chmCrop: num  21.2 23.9 23.8 22.4 23.9 ...</code></pre>
<p>When we use the <code>extract()</code> function, R extracts the value for each pixel
located within the boundary of the polygon being used to perform the extraction
- in this case the <code>aoi_boundary_HARV</code> object (a single polygon). Here, the
function extracted values from 18,450 pixels.</p>
<p>We can create a histogram of tree height values within the boundary to better
understand the structure or height distribution of trees at our site. We will
use the column <code>HARV_chmCrop</code> from our data frame as our x values, as this
column represents the tree heights for each pixel.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb21-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb21-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb21-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">data =</span> tree_height, <span class="fu">aes</span>(<span class="at">x =</span> HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb21-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb21-3" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Histogram of CHM Height Values (m)&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb21-4" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Tree Height&quot;</span>) <span class="sc">+</span></span>
<span id="cb21-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb21-5" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Frequency of Pixels&quot;</span>)</span></code></pre></div>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="08-geospatial-II_files/figure-html/view-extract-histogram-1.png" width="672" /></p>
<p>We can also use the <code>summary()</code> function to view descriptive statistics
including min, max, and mean height values. These values help us better
understand vegetation at our field site.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb23-1" tabindex="-1"></a><span class="fu">summary</span>(tree_height<span class="sc">$</span>HARV_chmCrop)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    2.03   21.36   22.81   22.43   23.97   38.17</code></pre>
<p><strong>Summarize Extracted Raster Values</strong></p>
<p>We often want to extract summary values from a raster. We can tell R the type
of summary statistic we are interested in using the <code>fun =</code> argument. Let’s
extract a mean height value for our AOI.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb25-1" tabindex="-1"></a>mean_tree_height_AOI <span class="ot">&lt;-</span> <span class="fu">extract</span>(<span class="at">x =</span> CHM_HARV, <span class="at">y =</span> aoi_boundary_HARV,</span>
<span id="cb25-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb25-2" tabindex="-1"></a>                                <span class="at">fun =</span> mean)</span>
<span id="cb25-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb25-3" tabindex="-1"></a></span>
<span id="cb25-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb25-4" tabindex="-1"></a>mean_tree_height_AOI</span></code></pre></div>
<pre><code>##   ID HARV_chmCrop
## 1  1     22.43018</code></pre>
<p>It appears that the mean height value, extracted from our LiDAR data derived
canopy height model is 22.43 meters.</p>
<p><strong>Extract Data using x,y Locations</strong></p>
<p>We can also extract pixel values from a raster by defining a buffer or area
surrounding individual point locations using the <code>st_buffer()</code> function. To do
this we define the summary argument (<code>fun = mean</code>) and the buffer distance
(<code>dist = 20</code>) which represents the radius of a circular region around each
point. By default, the units of the buffer are the same units as the data’s
CRS. All pixels that are touched by the buffer region are included in the
extract.</p>
<p><img src="fig/BufferCircular.png" alt="Image shows raster information extraction using 20m buffer region." />
Image Source: National Ecological Observatory Network (NEON)</p>
<p>Let’s put this into practice by figuring out the mean tree height in the 20m
around the tower location (<code>point_HARV</code>).</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb27-1" tabindex="-1"></a>mean_tree_height_tower <span class="ot">&lt;-</span> <span class="fu">extract</span>(<span class="at">x =</span> CHM_HARV,</span>
<span id="cb27-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb27-2" tabindex="-1"></a>                                  <span class="at">y =</span> <span class="fu">st_buffer</span>(point_HARV, <span class="at">dist =</span> <span class="dv">20</span>),</span>
<span id="cb27-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb27-3" tabindex="-1"></a>                                  <span class="at">fun =</span> mean)</span>
<span id="cb27-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb27-4" tabindex="-1"></a></span>
<span id="cb27-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb27-5" tabindex="-1"></a>mean_tree_height_tower</span></code></pre></div>
<pre><code>##   ID HARV_chmCrop
## 1  1     22.38806</code></pre>
</div>
<div id="in-class-challenge-2-extract-raster-height-values-for-plot-locations" class="section level3 hasAnchor" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> In class challenge 2: Extract Raster Height Values For Plot Locations<a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-2-extract-raster-height-values-for-plot-locations" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Use the plot locations object (<code>plot_locations_sp_HARV</code>) to extract an
average tree height for the area within 20 m of each vegetation plot location
in the study area. Because there are multiple plot locations, there will be
multiple averages returned.</p></li>
<li><p>Create a plot showing the mean tree height of each area.</p></li>
</ol>
<p><strong>Solution</strong></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-1" tabindex="-1"></a><span class="co"># extract data at each plot location</span></span>
<span id="cb29-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-2" tabindex="-1"></a>mean_tree_height_plots_HARV <span class="ot">&lt;-</span> <span class="fu">extract</span>(<span class="at">x =</span> CHM_HARV,</span>
<span id="cb29-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-3" tabindex="-1"></a>                                       <span class="at">y =</span> <span class="fu">st_buffer</span>(plot_locations_sp_HARV,</span>
<span id="cb29-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-4" tabindex="-1"></a>                                                     <span class="at">dist =</span> <span class="dv">20</span>),</span>
<span id="cb29-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-5" tabindex="-1"></a>                                       <span class="at">fun =</span> mean)</span>
<span id="cb29-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-6" tabindex="-1"></a></span>
<span id="cb29-7"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-7" tabindex="-1"></a><span class="co"># view data</span></span>
<span id="cb29-8"><a href="geospatial-data-ii-vector-raster-integration.html#cb29-8" tabindex="-1"></a>mean_tree_height_plots_HARV</span></code></pre></div>
<pre><code>##    ID HARV_chmCrop
## 1   1          NaN
## 2   2     23.96756
## 3   3     22.34937
## 4   4     16.49739
## 5   5     21.54419
## 6   6     19.16772
## 7   7     20.61651
## 8   8     21.61439
## 9   9     12.23006
## 10 10     19.13398
## 11 11     21.36966
## 12 12     19.32084
## 13 13     17.25975
## 14 14     20.47120
## 15 15     12.68301
## 16 16     15.51888
## 17 17     18.90894
## 18 18     18.19369
## 19 19     19.67441
## 20 20     20.23245
## 21 21     20.44984</code></pre>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-1" tabindex="-1"></a><span class="co"># plot data</span></span>
<span id="cb31-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> mean_tree_height_plots_HARV, <span class="fu">aes</span>(ID, HARV_chmCrop)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-3" tabindex="-1"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<span id="cb31-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Mean Tree Height at each Plot&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-5" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Plot ID&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb31-6" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Tree Height (m)&quot;</span>)</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_col()`).</code></pre>
<p><img src="08-geospatial-II_files/figure-html/hist-tree-height-veg-plot-1.png" width="672" />
On Wednesday we will continue learning skills for vector-raster itegration.</p>
<p><strong>Spatial Data in Text Format</strong></p>
<p>We would like to:</p>
<ul>
<li>Create a map of these plot locations, but we only have a .csv of their locations.</li>
<li>Export the data in an ESRI <code>shapefile</code> format to share with our colleagues. This
<code>shapefile</code> can be imported into most GIS software.</li>
<li>Create a map showing vegetation height with plot locations layered on top.</li>
</ul>
<p>Spatial data are sometimes stored in a text file format (<code>.txt</code> or <code>.csv</code>). If
the text file has an associated <code>x</code> and <code>y</code> location column, then we can
convert it into an <code>sf</code> spatial object. The <code>sf</code> object allows us to store both
the <code>x,y</code> values that represent the coordinate location of each point and the
associated attribute data - or columns describing each feature in the spatial
object.</p>
<p><strong>Import .csv</strong></p>
<p>The <code>HARV_PlotLocations.csv</code> file contains <code>x, y</code> (point) locations for study
plot where NEON collects data on
<a href="https://www.neonscience.org/data-collection/terrestrial-organismal-sampling">vegetation and other ecological metics</a>.</p>
<p>To begin let’s import a <code>.csv</code> file that contains plot coordinate <code>x, y</code>
locations at the NEON Harvard Forest Field Site (<code>HARV_PlotLocations.csv</code>) and
look at the structure of that new object:</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb33-1" tabindex="-1"></a>plot_locations_HARV <span class="ot">&lt;-</span></span>
<span id="cb33-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb33-2" tabindex="-1"></a>  <span class="fu">read.csv</span>(<span class="st">&quot;data/NEON-DS-Site-Layout-Files/HARV/HARV_PlotLocations.csv&quot;</span>)</span>
<span id="cb33-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb33-3" tabindex="-1"></a></span>
<span id="cb33-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb33-4" tabindex="-1"></a><span class="fu">str</span>(plot_locations_HARV)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    21 obs. of  16 variables:
##  $ easting   : num  731405 731934 731754 731724 732125 ...
##  $ northing  : num  4713456 4713415 4713115 4713595 4713846 ...
##  $ geodeticDa: chr  &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot; ...
##  $ utmZone   : chr  &quot;18N&quot; &quot;18N&quot; &quot;18N&quot; &quot;18N&quot; ...
##  $ plotID    : chr  &quot;HARV_015&quot; &quot;HARV_033&quot; &quot;HARV_034&quot; &quot;HARV_035&quot; ...
##  $ stateProvi: chr  &quot;MA&quot; &quot;MA&quot; &quot;MA&quot; &quot;MA&quot; ...
##  $ county    : chr  &quot;Worcester&quot; &quot;Worcester&quot; &quot;Worcester&quot; &quot;Worcester&quot; ...
##  $ domainName: chr  &quot;Northeast&quot; &quot;Northeast&quot; &quot;Northeast&quot; &quot;Northeast&quot; ...
##  $ domainID  : chr  &quot;D01&quot; &quot;D01&quot; &quot;D01&quot; &quot;D01&quot; ...
##  $ siteID    : chr  &quot;HARV&quot; &quot;HARV&quot; &quot;HARV&quot; &quot;HARV&quot; ...
##  $ plotType  : chr  &quot;distributed&quot; &quot;tower&quot; &quot;tower&quot; &quot;tower&quot; ...
##  $ subtype   : chr  &quot;basePlot&quot; &quot;basePlot&quot; &quot;basePlot&quot; &quot;basePlot&quot; ...
##  $ plotSize  : int  1600 1600 1600 1600 1600 1600 1600 1600 1600 1600 ...
##  $ elevation : num  332 342 348 334 353 ...
##  $ soilTypeOr: chr  &quot;Inceptisols&quot; &quot;Inceptisols&quot; &quot;Inceptisols&quot; &quot;Histosols&quot; ...
##  $ plotdim_m : int  40 40 40 40 40 40 40 40 40 40 ...</code></pre>
<p>We now have a data frame that contains 21 locations (rows) and 16 variables
(attributes). Note that all of our character data was imported into R as
character (text) data. Next, let’s explore the dataframe to determine whether
it contains columns with coordinate values. If we are lucky, our <code>.csv</code> will
contain columns labeled:</p>
<ul>
<li>“X” and “Y” OR</li>
<li>Latitude and Longitude OR</li>
<li>easting and northing (UTM coordinates)</li>
</ul>
<p>Let’s check out the column names of our dataframe.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb35-1" tabindex="-1"></a><span class="fu">names</span>(plot_locations_HARV)</span></code></pre></div>
<pre><code>##  [1] &quot;easting&quot;    &quot;northing&quot;   &quot;geodeticDa&quot; &quot;utmZone&quot;    &quot;plotID&quot;    
##  [6] &quot;stateProvi&quot; &quot;county&quot;     &quot;domainName&quot; &quot;domainID&quot;   &quot;siteID&quot;    
## [11] &quot;plotType&quot;   &quot;subtype&quot;    &quot;plotSize&quot;   &quot;elevation&quot;  &quot;soilTypeOr&quot;
## [16] &quot;plotdim_m&quot;</code></pre>
<p><strong>Identify X,Y Location Columns</strong></p>
<p>Our column names include several fields that might contain spatial information.
The <code>plot_locations_HARV$easting</code> and <code>plot_locations_HARV$northing</code> columns
contain coordinate values. We can confirm this by looking at the first six rows
of our data.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb37-1" tabindex="-1"></a><span class="fu">head</span>(plot_locations_HARV<span class="sc">$</span>easting)</span></code></pre></div>
<pre><code>## [1] 731405.3 731934.3 731754.3 731724.3 732125.3 731634.3</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb39-1" tabindex="-1"></a><span class="fu">head</span>(plot_locations_HARV<span class="sc">$</span>northing)</span></code></pre></div>
<pre><code>## [1] 4713456 4713415 4713115 4713595 4713846 4713295</code></pre>
<p>We have coordinate values in our data frame. In order to convert our data frame
to an <code>sf</code> object, we also need to know the CRS associated with those
coordinate values.</p>
<p>There are several ways to figure out the CRS of spatial data in text format.</p>
<ol style="list-style-type: decimal">
<li>We can check the file metadata in hopes that the CRS was recorded in the
data.</li>
<li>We can explore the file itself to see if CRS information is embedded in the
file header or somewhere in the data columns.</li>
</ol>
<p>Following the <code>easting</code> and <code>northing</code> columns, there is a <code>geodeticDa</code> and a
<code>utmZone</code> column. These appear to contain CRS information (<code>datum</code> and
<code>projection</code>). Let’s view those next.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb41-1" tabindex="-1"></a><span class="fu">head</span>(plot_locations_HARV<span class="sc">$</span>geodeticDa)</span></code></pre></div>
<pre><code>## [1] &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot; &quot;WGS84&quot;</code></pre>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb43-1" tabindex="-1"></a><span class="fu">head</span>(plot_locations_HARV<span class="sc">$</span>utmZone)</span></code></pre></div>
<pre><code>## [1] &quot;18N&quot; &quot;18N&quot; &quot;18N&quot; &quot;18N&quot; &quot;18N&quot; &quot;18N&quot;</code></pre>
<p>It is not typical to store CRS information in a column. But this particular
file contains CRS information this way. The <code>geodeticDa</code> and <code>utmZone</code> columns
contain the information that helps us determine the CRS:</p>
<ul>
<li><code>geodeticDa</code>: WGS84 – this is geodetic datum WGS84</li>
<li><code>utmZone</code>: 18</li>
</ul>
<p>To create the <code>proj4</code> associated with UTM Zone 18 WGS84 we can look up the
projection on the
<a href="https://spatialreference.org/ref/epsg/32618/">Spatial Reference website</a>,
which contains a list of CRS formats for each projection. From here, we can
download the proj4 string for UTM Zone 18N WGS84 by clicking the proj link.</p>
<p>However, if we have other data in the UTM Zone 18N projection, it’s much easier
to use the <code>st_crs()</code> function to extract the CRS in <code>proj4</code> format from that
object and assign it to our new spatial object. We’ve seen this CRS before with
our Harvard Forest study site (<code>point_HARV</code>).</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb45-1" tabindex="-1"></a><span class="fu">st_crs</span>(point_HARV)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 / UTM zone 18N 
##   wkt:
## PROJCRS[&quot;WGS 84 / UTM zone 18N&quot;,
##     BASEGEOGCRS[&quot;WGS 84&quot;,
##         DATUM[&quot;World Geodetic System 1984&quot;,
##             ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##                 LENGTHUNIT[&quot;metre&quot;,1]]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         ID[&quot;EPSG&quot;,4326]],
##     CONVERSION[&quot;UTM zone 18N&quot;,
##         METHOD[&quot;Transverse Mercator&quot;,
##             ID[&quot;EPSG&quot;,9807]],
##         PARAMETER[&quot;Latitude of natural origin&quot;,0,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8801]],
##         PARAMETER[&quot;Longitude of natural origin&quot;,-75,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8802]],
##         PARAMETER[&quot;Scale factor at natural origin&quot;,0.9996,
##             SCALEUNIT[&quot;unity&quot;,1],
##             ID[&quot;EPSG&quot;,8805]],
##         PARAMETER[&quot;False easting&quot;,500000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8806]],
##         PARAMETER[&quot;False northing&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8807]]],
##     CS[Cartesian,2],
##         AXIS[&quot;(E)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         AXIS[&quot;(N)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##     ID[&quot;EPSG&quot;,32618]]</code></pre>
<p>The output above shows that the points vector layer is in UTM zone 18N. We can
thus use the CRS from that spatial object to convert our non-spatial dataframe
into an <code>sf</code> object.</p>
<p>Next, let’s create a <code>crs</code> object that we can use to define the CRS of our <code>sf</code>
object when we create it.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb47-1" tabindex="-1"></a>utm18nCRS <span class="ot">&lt;-</span> <span class="fu">st_crs</span>(point_HARV)</span>
<span id="cb47-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb47-2" tabindex="-1"></a>utm18nCRS</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 / UTM zone 18N 
##   wkt:
## PROJCRS[&quot;WGS 84 / UTM zone 18N&quot;,
##     BASEGEOGCRS[&quot;WGS 84&quot;,
##         DATUM[&quot;World Geodetic System 1984&quot;,
##             ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##                 LENGTHUNIT[&quot;metre&quot;,1]]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         ID[&quot;EPSG&quot;,4326]],
##     CONVERSION[&quot;UTM zone 18N&quot;,
##         METHOD[&quot;Transverse Mercator&quot;,
##             ID[&quot;EPSG&quot;,9807]],
##         PARAMETER[&quot;Latitude of natural origin&quot;,0,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8801]],
##         PARAMETER[&quot;Longitude of natural origin&quot;,-75,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8802]],
##         PARAMETER[&quot;Scale factor at natural origin&quot;,0.9996,
##             SCALEUNIT[&quot;unity&quot;,1],
##             ID[&quot;EPSG&quot;,8805]],
##         PARAMETER[&quot;False easting&quot;,500000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8806]],
##         PARAMETER[&quot;False northing&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8807]]],
##     CS[Cartesian,2],
##         AXIS[&quot;(E)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         AXIS[&quot;(N)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##     ID[&quot;EPSG&quot;,32618]]</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb49-1" tabindex="-1"></a><span class="fu">class</span>(utm18nCRS)</span></code></pre></div>
<pre><code>## [1] &quot;crs&quot;</code></pre>
<p>** .csv to sf object**</p>
<p>Next, let’s convert our dataframe into an <code>sf</code> object. To do this, we need to
specify:</p>
<ol style="list-style-type: decimal">
<li>The columns containing X (<code>easting</code>) and Y (<code>northing</code>) coordinate values</li>
<li>The CRS that the column coordinate represent (units are included in the CRS) - stored in our <code>utmCRS</code> object.</li>
</ol>
<p>We will use the <code>st_as_sf()</code> function to perform the conversion.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb51-1" tabindex="-1"></a>plot_locations_sp_HARV <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(plot_locations_HARV,</span>
<span id="cb51-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb51-2" tabindex="-1"></a>                                   <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;easting&quot;</span>, <span class="st">&quot;northing&quot;</span>),</span>
<span id="cb51-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb51-3" tabindex="-1"></a>                                   <span class="at">crs =</span> utm18nCRS)</span></code></pre></div>
<p>We should double check the CRS to make sure it is correct.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb52-1" tabindex="-1"></a><span class="fu">st_crs</span>(plot_locations_sp_HARV)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 / UTM zone 18N 
##   wkt:
## PROJCRS[&quot;WGS 84 / UTM zone 18N&quot;,
##     BASEGEOGCRS[&quot;WGS 84&quot;,
##         DATUM[&quot;World Geodetic System 1984&quot;,
##             ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##                 LENGTHUNIT[&quot;metre&quot;,1]]],
##         PRIMEM[&quot;Greenwich&quot;,0,
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         ID[&quot;EPSG&quot;,4326]],
##     CONVERSION[&quot;UTM zone 18N&quot;,
##         METHOD[&quot;Transverse Mercator&quot;,
##             ID[&quot;EPSG&quot;,9807]],
##         PARAMETER[&quot;Latitude of natural origin&quot;,0,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8801]],
##         PARAMETER[&quot;Longitude of natural origin&quot;,-75,
##             ANGLEUNIT[&quot;Degree&quot;,0.0174532925199433],
##             ID[&quot;EPSG&quot;,8802]],
##         PARAMETER[&quot;Scale factor at natural origin&quot;,0.9996,
##             SCALEUNIT[&quot;unity&quot;,1],
##             ID[&quot;EPSG&quot;,8805]],
##         PARAMETER[&quot;False easting&quot;,500000,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8806]],
##         PARAMETER[&quot;False northing&quot;,0,
##             LENGTHUNIT[&quot;metre&quot;,1],
##             ID[&quot;EPSG&quot;,8807]]],
##     CS[Cartesian,2],
##         AXIS[&quot;(E)&quot;,east,
##             ORDER[1],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##         AXIS[&quot;(N)&quot;,north,
##             ORDER[2],
##             LENGTHUNIT[&quot;metre&quot;,1]],
##     ID[&quot;EPSG&quot;,32618]]</code></pre>
<p><strong>Plot Spatial Object</strong></p>
<p>We now have a spatial R object, we can plot our newly created spatial object.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb54-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb54-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb54-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> plot_locations_sp_HARV) <span class="sc">+</span></span>
<span id="cb54-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb54-3" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Map of Plot Locations&quot;</span>)</span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/plot-data-points-1.png" width="672" /></p>
</div>
<div id="in-class-challenge-4-import-plot-additional-points" class="section level3 hasAnchor" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> In class challenge 4: Import &amp; Plot Additional Points<a href="geospatial-data-ii-vector-raster-integration.html#in-class-challenge-4-import-plot-additional-points" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We want to add two phenology plots to our existing map of vegetation plot
locations.</p>
<p>Import the .csv: <code>HARV/HARV_2NewPhenPlots.csv</code> into R and do the following:</p>
<ol style="list-style-type: decimal">
<li>Find the X and Y coordinate locations. Which value is X and which value is
Y?</li>
<li>These data were collected in a geographic coordinate system (WGS84). Convert
the dataframe into an <code>sf</code> object. HINT: check the crs of our other spatial objects to see if you can extract that crs to use to assign to the new data.</li>
<li>Plot the new points with the plot location points from above. Be sure to add
a legend. Use a different symbol for the 2 new points!</li>
</ol>
<p>If you have extra time, feel free to add roads and other layers to your map!</p>
<p><strong>Solution</strong></p>
<ol style="list-style-type: decimal">
<li>First we will read in the new csv file and look at the data structure.</li>
</ol>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb55-1" tabindex="-1"></a>newplot_locations_HARV <span class="ot">&lt;-</span></span>
<span id="cb55-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb55-2" tabindex="-1"></a>  <span class="fu">read.csv</span>(<span class="st">&quot;data/NEON-DS-Site-Layout-Files/HARV/HARV_2NewPhenPlots.csv&quot;</span>)</span>
<span id="cb55-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb55-3" tabindex="-1"></a><span class="fu">str</span>(newplot_locations_HARV)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2 obs. of  13 variables:
##  $ decimalLat: num  42.5 42.5
##  $ decimalLon: num  -72.2 -72.2
##  $ country   : chr  &quot;unitedStates&quot; &quot;unitedStates&quot;
##  $ stateProvi: chr  &quot;MA&quot; &quot;MA&quot;
##  $ county    : chr  &quot;Worcester&quot; &quot;Worcester&quot;
##  $ domainName: chr  &quot;Northeast&quot; &quot;Northeast&quot;
##  $ domainID  : chr  &quot;D01&quot; &quot;D01&quot;
##  $ siteID    : chr  &quot;HARV&quot; &quot;HARV&quot;
##  $ plotType  : chr  &quot;tower&quot; &quot;tower&quot;
##  $ subtype   : chr  &quot;phenology&quot; &quot;phenology&quot;
##  $ plotSize  : int  40000 40000
##  $ plotDimens: chr  &quot;200m x 200m&quot; &quot;200m x 200m&quot;
##  $ elevation : num  358 346</code></pre>
<ol start="2" style="list-style-type: decimal">
<li>The US boundary data we worked with previously is in a geographic WGS84 CRS. We
can use that data to establish a CRS for this data. First we will extract the
CRS from the <code>country_boundary_US</code> object and confirm that it is WGS84.</li>
</ol>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb57-1" tabindex="-1"></a>geogCRS <span class="ot">&lt;-</span> <span class="fu">st_crs</span>(country_boundary_US)</span>
<span id="cb57-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb57-2" tabindex="-1"></a>geogCRS</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 
##   wkt:
## GEOGCRS[&quot;WGS 84&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     ID[&quot;EPSG&quot;,4326]]</code></pre>
<p>Then we will convert our new data to a spatial dataframe, using the <code>geogCRS</code>
object as our CRS.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb59-1" tabindex="-1"></a>newPlot.Sp.HARV <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(newplot_locations_HARV,</span>
<span id="cb59-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb59-2" tabindex="-1"></a>                            <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;decimalLon&quot;</span>, <span class="st">&quot;decimalLat&quot;</span>),</span>
<span id="cb59-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb59-3" tabindex="-1"></a>                            <span class="at">crs =</span> geogCRS)</span></code></pre></div>
<p>Next we’ll confirm that the CRS for our new object is correct.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb60-1" tabindex="-1"></a><span class="fu">st_crs</span>(newPlot.Sp.HARV)</span></code></pre></div>
<pre><code>## Coordinate Reference System:
##   User input: WGS 84 
##   wkt:
## GEOGCRS[&quot;WGS 84&quot;,
##     DATUM[&quot;World Geodetic System 1984&quot;,
##         ELLIPSOID[&quot;WGS 84&quot;,6378137,298.257223563,
##             LENGTHUNIT[&quot;metre&quot;,1]]],
##     PRIMEM[&quot;Greenwich&quot;,0,
##         ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     CS[ellipsoidal,2],
##         AXIS[&quot;latitude&quot;,north,
##             ORDER[1],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##         AXIS[&quot;longitude&quot;,east,
##             ORDER[2],
##             ANGLEUNIT[&quot;degree&quot;,0.0174532925199433]],
##     ID[&quot;EPSG&quot;,4326]]</code></pre>
<p>We will be adding these new data points to the plot we created before. The data
for the earlier plot was in UTM. Since we’re using <code>ggplot</code>, it will reproject
the data for us.</p>
<ol start="3" style="list-style-type: decimal">
<li>Now we can create our plot.</li>
</ol>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb62-1" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb62-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb62-2" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> plot_locations_sp_HARV, <span class="at">color =</span> <span class="st">&quot;orange&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb62-3" tabindex="-1"></a>  <span class="fu">geom_sf</span>(<span class="at">data =</span> newPlot.Sp.HARV, <span class="at">color =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb62-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb62-4" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Map of All Plot Locations&quot;</span>)</span></code></pre></div>
<p><img src="08-geospatial-II_files/figure-html/plot-locations-harv-orange-1.png" width="672" /></p>
<p><strong>Export to an ESRI <code>shapefile</code></strong></p>
<p>We can write an R spatial object to an ESRI <code>shapefile</code> using the <code>st_write</code> function
in <code>sf</code>. To do this we need the following arguments:</p>
<ul>
<li>the name of the spatial object (<code>plot_locations_sp_HARV</code>)</li>
<li>the directory where we want to save our ESRI <code>shapefile</code> (to use <code>current = getwd()</code>
or you can specify a different path)</li>
<li>the name of the new ESRI <code>shapefile</code> (<code>PlotLocations_HARV</code>)</li>
<li>the driver which specifies the file format (ESRI Shapefile)</li>
</ul>
<p>We can now export the spatial object as an ESRI <code>shapefile</code>.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb63-1" tabindex="-1"></a><span class="fu">st_write</span>(plot_locations_sp_HARV,</span>
<span id="cb63-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb63-2" tabindex="-1"></a>         <span class="st">&quot;data/PlotLocations_HARV.shp&quot;</span>, <span class="at">driver =</span> <span class="st">&quot;ESRI Shapefile&quot;</span>, <span class="at">append=</span><span class="cn">FALSE</span>)</span></code></pre></div>
</div>
</div>
<div id="dicussion-reflection-debugging-in-r" class="section level2 hasAnchor" number="9.2">
<h2><span class="header-section-number">9.2</span> Dicussion &amp; Reflection: Debugging in R<a href="geospatial-data-ii-vector-raster-integration.html#dicussion-reflection-debugging-in-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>How to use R’s debugging tools, handle errors, and avoid bugs</p>
<div id="basic-debugging-strategies" class="section level3 hasAnchor" number="9.2.1">
<h3><span class="header-section-number">9.2.1</span> 1) Basic debugging strategies<a href="geospatial-data-ii-vector-raster-integration.html#basic-debugging-strategies" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>Read and think about the error message. Sometimes it’s inscrutable, but often it just needs a bit of deciphering. Looking up a given error message on Stack Overflow or simply doing a web search with the exact message in double quotes can be a good strategy.</p></li>
<li><p>Fix errors from the top down - fix the first error that is reported, because later errors are often caused by the initial error. It’s common to have a string of many errors, which looks daunting, caused by a single initial error.</p></li>
<li><p>Is the bug reproducible - does it always happen in the same way at at the same point? It can help to restart R and see if the bug persists - this can sometimes help in figuring out if there is a scoping issue and we are using a global variable that we did not mean to.</p></li>
<li><p>Another basic strategy is to build up code in pieces (or tear it back in pieces to a simpler version). This allows you to isolate where the error is occurring.</p></li>
<li><p>If you’ve written your code modularly with lots of functions, you can test individual functions. Often the error will be in what gets passed into and out of each function.</p></li>
<li><p>You can have warnings printed as they occurred, rather than saved, using <code>options(warn = 1)</code>. This can help figure out where in a loop a warning is being generated. You can also have R convert warnings to error using <code>options(warn = 2)</code>.</p></li>
<li><p>At the beginning of time (the 1970s?), the standard debugging strategy was to insert print statements in one’s code to see the value of a variable and thereby decipher what could be going wrong. We have better tools nowadays, but this approach is still useful, particularly when you are having an issue with control statements (for loops, if/else).</p></li>
<li><p>R is a scripting language, so you can usually run your code line by line to figure out what is happening. This can be a decent approach, particularly for simple code. However, when you are trying to find errors that occur within a series of many nested function calls or when the errors involve variable scoping (how R looks for variables that are not local to a function), or in other complicated situations, using formal debugging tools can be much more effective. Finally, if the error occurs inside of functions provided by R, rather than ones you write, it can be hard to run the code in those functions line by line.</p></li>
</ol>
</div>
<div id="rs-interactive-debugging-tools" class="section level3 hasAnchor" number="9.2.2">
<h3><span class="header-section-number">9.2.2</span> R’s interactive debugging tools<a href="geospatial-data-ii-vector-raster-integration.html#rs-interactive-debugging-tools" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This section gives an overview of the various debugging tools.</p>
<p>Note that RStudio wraps all of functionality of these tools in its graphical interface, so you can use all the tools there, but the tools will be provided with some additional graphical functionality from RStudio.</p>
<div id="interactive-debugging-via-the-browser" class="section level4 hasAnchor" number="9.2.2.1">
<h4><span class="header-section-number">9.2.2.1</span> Interactive debugging via the browser<a href="geospatial-data-ii-vector-raster-integration.html#interactive-debugging-via-the-browser" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The core strategy for interactive debugging is to use the <em>browser</em> function, which pauses the current execution, and provides an interpreter, allowing you to view the current state of R. You can invoke <em>browser</em> in four ways</p>
<ul>
<li><p>by inserting a call to <code>browser()</code> in your code if you suspect where things are going wrong</p></li>
<li><p>by invoking the browser after every step of a function using <em>debug</em></p></li>
<li><p>by using <code>options(error = recover)</code> to invoke the browser when an error occurs</p></li>
<li><p>by temporarily modifying a function to allow browsing using <em>trace</em></p></li>
</ul>
<p>Once in the browser, you can execute any R commands you want. In particular, using <em>ls</em> to look at the objects residing in the current function environment, looking at the values of objects, and examining the classes of objects is often helpful.</p>
<p>Type Q in the Console to exit browser.</p>
</div>
<div id="using-debug-to-step-through-code" class="section level4 hasAnchor" number="9.2.2.2">
<h4><span class="header-section-number">9.2.2.2</span> Using <em>debug</em> to step through code<a href="geospatial-data-ii-vector-raster-integration.html#using-debug-to-step-through-code" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To step through a function, use <code>debug(nameOfFunction)</code>. Then run your code. When the function is executed, R will pause execution just before the first line of the function. You are now using the browser and can examine the state of R and execute R statements.</p>
<p>Once in the browser context, you can use ‘n’ or <return> to step to the next line, ‘f’ to finish executing the entire current function or current loop, ‘c’ to continue to any subsequent browser calls, or ‘Q’ to stop debugging. We’ll see this in the screencast demo.</p>
<p>To unflag the function so that calling it doesn’t invoke debug, use <code>undebug(nameOfFunction)</code>. In addition to working with functions you write you can use <em>debug</em> with standard R functions and functions from packages. For example you could do <code>debug(glm)</code>.</p>
<p>If you know you only want to run the function once in debugging mode (to avoid having to use <em>undebug</em>), use <code>debugonce(nameOfFunction)</code>.</p>
</div>
<div id="tracing-errors-in-the-call-stack" class="section level4 hasAnchor" number="9.2.2.3">
<h4><span class="header-section-number">9.2.2.3</span> Tracing errors in the call stack<a href="geospatial-data-ii-vector-raster-integration.html#tracing-errors-in-the-call-stack" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><em>traceback</em> and <em>recover</em> allow you to see the call stack at the time of the error - i.e., they will show you all the functions that have been called, in the order called. This helps pinpoint where in a series of function calls the error may be occurring.</p>
<p>If you’ve run the code and gotten an error, you can invoke <em>traceback</em> after things have gone awry. R will show you the call stack, which can help pinpoint where an error is occurring.</p>
<p>More helpful is to be able to browse within the call stack. To do this invoke <code>options(error = recover)</code> (potentially in your <em>.Rprofile</em> if you do a lot of programming). Then when an error occurs, <em>recover</em> gets called, usually from the function in which the error occurred. The call to <em>recover</em> allows you to navigate the stack of active function calls at the time of the error and browse within the desired call. You just enter the number of the call you’d like to enter (or 0 to exit). You can then look around in the frame of a given function, entering <return> when you want to return to the list of calls again.</p>
<p>You can also combine this with <code>options(warn = 2)</code>, which turns warnings into errors to get to the point where a warning was issued.</p>
</div>
<div id="using-trace-to-temporarily-insert-code" class="section level4 hasAnchor" number="9.2.2.4">
<h4><span class="header-section-number">9.2.2.4</span> Using <em>trace</em> to temporarily insert code<a href="geospatial-data-ii-vector-raster-integration.html#using-trace-to-temporarily-insert-code" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><em>trace</em> lets you temporarily insert code into a function (including standard R functions and functions in packages!) that can then be easily removed. You can use trace in a variety of ways.</p>
<p>The most flexible way to use <em>trace</em> is to use the argument <code>edit = TRUE</code> and then insert whatever code you want wherever you want in the function given as the first argument to <em>trace</em>. If I want to ensure I use a particular editor, such as emacs, I can use the argument <code>edit = “emacs”</code>. A standard approach would be to add a line with <code>browser()</code> at some point in the function to be able to step through the code from that point.</p>
<p>You can also use <em>trace</em> without directly editing the function. Here are a couple examples:</p>
<ul>
<li><code>trace(lm, recover)</code> # invoke <em>recover</em> when the function (<em>lm</em> in this case) starts</li>
<li><code>trace(lm, exit = browser)</code> # invoke <em>browser</em> when the function ends</li>
</ul>
<p>You call <em>untrace</em>, e.g., <code>untrace(lm)</code>, to remove the temporarily inserted code; otherwise it’s removed when the session ends.</p>
<p>To figure out why warnings are being issued, you can do <code>trace(warning, recover)</code> which will insert a call to <em>recover</em> whenever <em>warning</em> is called.</p>
<p>Of course you can manually change the code in a function without using <em>trace</em>, but it’s very easy to forget to change things back (and a pain to remember exactly what you changed) and hard to do this with functions in packages, so <em>trace</em> is a nice way to do things.</p>
</div>
</div>
<div id="some-common-causes-of-bugs" class="section level3 hasAnchor" number="9.2.3">
<h3><span class="header-section-number">9.2.3</span> Some common causes of bugs<a href="geospatial-data-ii-vector-raster-integration.html#some-common-causes-of-bugs" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Some of these are R-specific, while others are common to a variety of languages.</p>
<ul>
<li><p>Parenthesis mis-matches</p></li>
<li><p><code>[[...]]</code> vs. <code>[...]</code></p></li>
<li><p><code>==</code> vs. <code>=</code></p></li>
<li><p>Comparing real numbers exactly using <code>==</code> is dangerous because numbers on a computer are only represented to limited numerical precision. For example,</p></li>
<li><p>You expect a single value but execution of the code gives a vector</p></li>
<li><p>You want to compare an entire vector but your code just compares the first value (e.g., in an if statement) – consider using <em>identical</em> or <em>all.equal</em></p></li>
<li><p>Silent type conversion when you don’t want it, or lack of coercion where you’re expecting it</p></li>
<li><p>Using the wrong function or variable name</p></li>
<li><p>Giving unnamed arguments to a function in the wrong order</p></li>
<li><p>In an if-else statement, the <code>else</code> cannot be on its own line (unless all the code is enclosed in <code>{}</code>) because R will see the <code>if</code> part of the statement, which is a valid R statement, will execute that, and then will encounter the <code>else</code> and return an error.</p></li>
<li><p>Forgetting to define a variable in the environment of a function and having R, via lexical scoping, get that variable as a global variable from one of the enclosing environments. At best the types are not compatible and you get an error; at worst, you use a garbage value and the bug is hard to trace. In some cases your code may work fine when you develop the code (if the variable exists in the enclosing environment), but then may not work when you restart R if the variable no longer exists or is different.</p></li>
<li><p>R (usually helpfully) drops matrix and array dimensions that are extraneous. This can sometimes confuse later code that expects an object of a certain dimension.</p></li>
</ul>
</div>
<div id="tips-for-avoiding-bugs-and-catching-errors" class="section level3 hasAnchor" number="9.2.4">
<h3><span class="header-section-number">9.2.4</span> Tips for avoiding bugs and catching errors<a href="geospatial-data-ii-vector-raster-integration.html#tips-for-avoiding-bugs-and-catching-errors" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="practice-defensive-programming" class="section level4 hasAnchor" number="9.2.4.1">
<h4><span class="header-section-number">9.2.4.1</span> Practice defensive programming<a href="geospatial-data-ii-vector-raster-integration.html#practice-defensive-programming" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>When writing functions, and software more generally, you’ll want to warn the user or stop execution when there is an error and exit gracefully, giving the user some idea of what happened. Here are some things to consider:</p>
<ul>
<li>check function inputs and warn users if the code will do something they might not expect or makes particular choices;</li>
<li>check inputs to <code>if</code> and the ranges in <code>for</code> loops;</li>
<li>provide reasonable default arguments;</li>
<li>document the range of valid inputs;</li>
<li>check that the output produced is valid; and</li>
<li>stop execution based on checks and give an informative error message.</li>
</ul>
<p>The <em>warning</em> and <em>stop</em> functions allow you to do stop execution and issue warnings or errors in the same way that base R code does; in general they would be called based on an <code>if</code> statement. More succinctly, to stop code if a condition is not satisfied, you can use <em>stopifnot</em>. This allow you to catch errors that can be anticipated. I also recommend using some of R’s packages for doing such checks, such as <em>assertthat</em>, <em>assertr</em>, and <em>checkmate</em>.</p>
<p>Here’s an example of building a robust square root function using <em>stop</em> and <em>warning</em>. Note you could use <code>stopifnot(is.numeric(x))</code> or <code>assert_that(is.numeric(x))</code> in place of one of the checks here.</p>
</div>
<div id="catch-run-time-errors-with-try-statements" class="section level4 hasAnchor" number="9.2.4.2">
<h4><span class="header-section-number">9.2.4.2</span> Catch run-time errors with <code>try</code> statements<a href="geospatial-data-ii-vector-raster-integration.html#catch-run-time-errors-with-try-statements" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Also, sometimes a function you call will fail, but you want to continue execution. For example, suppose you are doing a stratified analysis in which you take subsets of your data based on some categorical variable and fit a statistical model for each value of the categorical variable. If some of the subsets have no or very few observations, the statistical model fitting might fail. To do this, you might be using a for loop or <em>lapply</em>. You want your code to continue and fit the model for the rest of the cases even if one (or more) of the cases cannot be fit. You can wrap the function call that may fail within the <code>try</code> function (or <code>tryCatch</code>) and then your code won’t stop, even when an error occurs. Here’s a toy example.</p>
<pre><code>## Error in lm.fit(x, y, offset = offset, singular.ok = singular.ok, ...) : 
##   0 (non-NA) cases</code></pre>
<p>The seventh stratum had no observations, so that call to <em>lm</em> failed, but the loop continued because we ‘caught’ the error with <em>try</em>. In this example, we could have checked the sample size for the subset before doing the regression, but in other contexts, we may not have an easy way to check in advance whether the function call will fail.</p>
<p>You can also use <code>browser</code> with <code>try</code> to inspect what is breaking your code.</p>
</div>
<div id="find-and-avoid-global-variables" class="section level4 hasAnchor" number="9.2.4.3">
<h4><span class="header-section-number">9.2.4.3</span> Find and avoid global variables<a href="geospatial-data-ii-vector-raster-integration.html#find-and-avoid-global-variables" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>In general, using global variables (variables that are not created or passed into a function) results in code that is not robust. Results will change if you or a user modifies that global variable, usually without realizing/remembering that a function depends on it.</p>
<p>Start every script by removing any lingering objects.</p>
<p>This can also be accomplished with the “bloom” in the environment panel in R studio.</p>
<p>To be systematic, the <em>codetools</em> library has some useful tools for checking code, including a function, <em>findGlobals</em>, that let’s you look for the use of global variables</p>
</div>
<div id="miscellaneous-tips" class="section level4 hasAnchor" number="9.2.4.4">
<h4><span class="header-section-number">9.2.4.4</span> Miscellaneous tips<a href="geospatial-data-ii-vector-raster-integration.html#miscellaneous-tips" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>Use core R functionality and algorithms already coded. Figure out if a functionality already exists in (or can be adapted from) an R package (or potentially in a C/Fortran library/package): code that is part of standard mathematical/numerical packages will probably be more efficient and bug-free than anything you would write.</li>
<li>Code in a modular fashion, making good use of functions, so that you don’t need to debug the same code multiple times. Smaller functions are easier to debug, easier to understand, and can be combined in a modular fashion (like the UNIX utilities).</li>
<li>Write code for clarity and accuracy first; then worry about efficiency. Write an initial version of the code in the simplest way, without trying to be efficient (e.g., you might use for loops even if you’re coding in R); then make a second version that employs efficiency tricks and check that both produce the same output.</li>
<li>Plan out your code in advance, including all special cases/possibilities.</li>
<li>Write tests for your code early in the process.</li>
<li>Build up code in pieces, testing along the way. Make big changes in small steps, sequentially checking to see if the code has broken on test case(s).</li>
<li>Be careful that the conditions of <code>if</code> statements and the sequences of <code>for</code> loops are robust when they involve evaluating R code.</li>
<li>Don’t hard code numbers - use variables (e.g., number of iterations, parameter values in simulations), even if you don’t expect to change the value, as this makes the code more readable and reduces bugs when you use the same number multiple times; e.g. <code>speedOfLight &lt;- 3e8</code> or <code>nIts &lt;- 1000</code>.</li>
</ul>
</div>
</div>
<div id="how-to-get-help-online" class="section level3 hasAnchor" number="9.2.5">
<h3><span class="header-section-number">9.2.5</span> How to get help online<a href="geospatial-data-ii-vector-raster-integration.html#how-to-get-help-online" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="mailing-lists-and-online-forums" class="section level4 hasAnchor" number="9.2.5.1">
<h4><span class="header-section-number">9.2.5.1</span> Mailing lists and online forums<a href="geospatial-data-ii-vector-raster-integration.html#mailing-lists-and-online-forums" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>There are several mailing lists that have lots of useful postings. In general if you have an error, others have already posted about it.</p>
<ul>
<li><a href="http://stackoverflow.com">Stack overflow</a>: R stuff will be tagged with ‘R’: <a href="http://stackoverflow.com/questions/tagged/r">http://stackoverflow.com/questions/tagged/r</a></li>
<li>R help special interest groups (SIG) such as r-sig-hpc (high performance computing), r-sig-mac (R on Macs), etc. Unfortunately these are not easily searchable, but can often be found by simple web searchs, potentially including the name of the SIG in the search.</li>
<li>Simple web searches: You may want to include “in R”, with the quotes in the search. To search a SIG you might include the name of the SIG in the search string</li>
</ul>
</div>
<div id="asking-questions-online" class="section level4 hasAnchor" number="9.2.5.2">
<h4><span class="header-section-number">9.2.5.2</span> Asking questions online<a href="geospatial-data-ii-vector-raster-integration.html#asking-questions-online" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If you’ve searched the archive and haven’t found an answer to your problem, you can often get help by posting to the R-help mailing list or one of the other lists mentioned above. A few guidelines (generally relevant when posting to mailing lists beyond just the R lists):</p>
<p>Search the archives and look through relevant R books or manuals first.</p>
<p>Boil your problem down to the essence of the problem, giving an example, including the output and error message</p>
<p>Say what version of R, what operating system and what operating system version you’re using. Both <em>sessionInfo</em> and <em>Sys.info</em> can be helpful for getting this information.</p>
<p>Read the <a href="https://www.r-project.org/posting-guide.html">R mailing list posting guide</a>.</p>
<p>The R mailing lists are a way to get free advice from the experts, who include some of the world’s most knowledgeable R experts - seriously - members of the R core development team contribute frequently. The cost is that you should do your homework and that sometimes the responses you get may be blunt, along the lines of “read the manual”. I think it’s a pretty good tradeoff - where else do you get the foremost experts in a domain actually helping you?</p>
<div id="preclass-reflection-please-submit-short-answers-via-canvas-3" class="section level5 hasAnchor" number="9.2.5.2.1">
<h5><span class="header-section-number">9.2.5.2.1</span> Pre‑class reflection (please submit short answers via canvas)<a href="geospatial-data-ii-vector-raster-integration.html#preclass-reflection-please-submit-short-answers-via-canvas-3" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ol style="list-style-type: decimal">
<li><strong>Your debugging workflow.</strong> Describe the steps you currently take when code fails. Which step from the reading would most improve your process, and why?</li>
</ol>
</div>
<div id="inclass-smallgroup-prompts-2" class="section level5 hasAnchor" number="9.2.5.2.2">
<h5><span class="header-section-number">9.2.5.2.2</span> In‑class small‑group prompts<a href="geospatial-data-ii-vector-raster-integration.html#inclass-smallgroup-prompts-2" class="anchor-section" aria-label="Anchor link to header"></a></h5>
<ol style="list-style-type: decimal">
<li>Step through with browser() (10–12 min)</li>
</ol>
<p>Goal: Practice pausing and inspecting local state.</p>
<p>Add a breakpoint and re-run:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-1" tabindex="-1"></a>good <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb65-2"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-2" tabindex="-1"></a>  <span class="fu">browser</span>()               <span class="co"># step in: n (next), c (continue)</span></span>
<span id="cb65-3"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-3" tabindex="-1"></a>  y <span class="ot">&lt;-</span> x <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb65-4"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-4" tabindex="-1"></a>  <span class="fu">mean</span>(y, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb65-5"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-5" tabindex="-1"></a>}</span>
<span id="cb65-6"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-6" tabindex="-1"></a><span class="fu">debugonce</span>(good)</span>
<span id="cb65-7"><a href="geospatial-data-ii-vector-raster-integration.html#cb65-7" tabindex="-1"></a><span class="fu">good</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="cn">NA</span>, <span class="dv">4</span>))</span></code></pre></div>
<p>While paused:</p>
<ul>
<li>Inspect objects (ls(), str(x), class(x)), then step and re-inspect.</li>
<li>Change x in place and continue — what happens?</li>
<li>Remove the breakpoint and create a quick unit-style check that would have caught the bug earlier.</li>
</ul>
</div>
</div>
</div>
</div>
<div id="lab-spatial-data-2-working-with-oba-data-student-version" class="section level2 hasAnchor" number="9.3">
<h2><span class="header-section-number">9.3</span> Lab: Spatial data 2: Working with OBA data (Student Version)<a href="geospatial-data-ii-vector-raster-integration.html#lab-spatial-data-2-working-with-oba-data-student-version" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Conservation/ecology Topics</strong></p>
<ul>
<li>Species distributions</li>
</ul>
<p><strong>Computational Topics</strong>
- Convert a data frame to a spatial object.
- Plot multiple spatial layers.</p>
<p><strong>Lab part 1: Oregon bee atlas data exploration</strong></p>
<ul>
<li><p>1a. Import the OBA data. (remember it’s in the main data folder of the book and not in the labs folder, so you have to move back a folder)</p></li>
<li><p>1b. Find the columns related to genus and species and paste them together (with a space between) using the function paste(). Name the new column GenusSpecies.</p></li>
<li><p>1c. Use <code>sort()</code> and <code>unique()</code> to print the unique values of GenusSpecies in alphabetical order. How many species are there?</p></li>
</ul>
<p>Some specimens are not identified to species, only genus. How is this reflected in the data?</p>
<ul>
<li><p>1d. So many bees, so little time. Count up the occurrences of each bee species, and subset the data to bees that have been seen at least two times.
You can use the tidyverse or any other functions in R that you like. How many “species” are there?</p></li>
<li><p>1e. Google a few bee names (that have been seen &gt; 2 times) and find one with an a look that resonates with you.</p></li>
</ul>
<p>What is the name of your bee?</p>
<p>Import the photos into Rmarkdown below (hint: googling bee name “discover life” or “inat” can often get you a photo. Many bees will no have any photos :( use the format <img src="fig/***.png" alt="My spirt bee: ****" /></p>
<p><strong>Lab part 2: Plotting the distribution of your spirit bee.</strong></p>
<p>How that have chosen your spirit bee, we would like to plot it’s distribution. What is the crs of the data? Annoyingly it is not described anywhere in the spreadsheet (always list your crs in your data) but it is the same as what inat uses because all bees have a georeferenced plant host. If the data is in lat long, it is “unprojected” so only a datum will be listed.
DATUM: WGS84, unprojected lat long. EPSG code: 4326.</p>
<pre><code>## [1] &quot;GEOGCRS[\&quot;WGS 84\&quot;,\n    DATUM[\&quot;World Geodetic System 1984\&quot;,\n        ELLIPSOID[\&quot;WGS 84\&quot;,6378137,298.257223563,\n            LENGTHUNIT[\&quot;metre\&quot;,1]]],\n    PRIMEM[\&quot;Greenwich\&quot;,0,\n        ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433]],\n    CS[ellipsoidal,2],\n        AXIS[\&quot;geodetic latitude (Lat)\&quot;,north,\n            ORDER[1],\n            ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433]],\n        AXIS[\&quot;geodetic longitude (Lon)\&quot;,east,\n            ORDER[2],\n            ANGLEUNIT[\&quot;degree\&quot;,0.0174532925199433]],\n    USAGE[\n        SCOPE[\&quot;Horizontal component of 3D system.\&quot;],\n        AREA[\&quot;World.\&quot;],\n        BBOX[-90,-180,90,180]],\n    ID[\&quot;EPSG\&quot;,4326]]&quot;</code></pre>
<ul>
<li><p>2a. Extract the X and Y locations for your species only from the data and create a spatial object. Don’t forget to set the CRS!
Hint 1: consider what other data you would like to keep as attributes, for example what flower they were foraging on. Hint 2: Remember the lat is y and long is x.
Hint 3: You may want to rename the column names you can use, <code>colnames()</code> or <code>rename()</code> from dplyr and reassign the names. This is only if you don’t love the names they already have.</p></li>
<li><p>2b. Plot your exciting bee data!</p></li>
</ul>
<p>Not so exciting without some kind of background…</p>
<p>Luckily we can download basemaps into R using the map_data function in ggplot (among many others). There is an example for retrieving the Oregon county polygons.</p>
<ul>
<li>2c. Add your species’s points to your choice or an Oregon basemap.</li>
</ul>
<p><strong>Lab part 3: Cartography</strong></p>
<ul>
<li>3a. Here is your moment to explore your cartographic skills.</li>
</ul>
<ol style="list-style-type: decimal">
<li>Add the a spatial layer relevant to your final project (ex. fire perimeters) or one from the <a href="https://geohub.oregon.gov/">Oregon Geohub</a> and tweek the Oregon map in anyway that is useful/visually appealing. You may need to crop that layer to the extent of your species’s distribution.</li>
<li>Color your points according to some data attribute and add a legend (month collected, county, collector, associated plant, whatever you think is interesting). You may need to circle back to 2.1 to save
additional attributes when you converted the dataframe to a spatial object.</li>
<li>Fine-tune your map: add a title, make sure the legend label makes sense, add a scale bar (google “add scale bar map ggplot” and choose your favorite package). All maps must always have a scale bar. You can add a N arrow as well, though some cartographers argue that is only necessary if N isn’t at the top of the map.</li>
<li>Write a figure caption for your map explaining any interesting trends you see.</li>
<li>Export your cropped layer to a .shp so you can use it again for your final project.</li>
</ol>
<p>We are looking forward to seeing the maps you create!</p>
<p><strong>Lab part 4: Spatial summary statistics</strong>
For your final projects, you will likely need to come up with summary statistics that describes the areas around where bees are captured.</p>
<ul>
<li><p>4a. Using the distribution of your chosen bee and the a raster spatial layer from <a href="https://geohub.oregon.gov/">Oregon Geohub</a>, extract a meaningful summary statistics from your spatial layer within a buffer of 500, 750 1000 m.</p></li>
<li><p>4b. Create a plot that illustrates this summary data (box plot, barplot, scatter plot, historgram).</p></li>
<li><p>4c. Create a map of your cropped spatial data.</p></li>
</ul>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="geospatial-data-i-data-types-rasters-and-vector-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="string-processing-debugging.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
